### ISSUE TITLE
el-get-update doesn't update .loaddefs.el 

### ISSUE THREAD

**Issue by aspiers** [dimitri/el-get#1352]
If I do `M-x el-get-update rinari`, the `rinari` components of `~/.emacs.d/el-get/.loaddefs.el` don't get updated.  #446, #453, and #543 all look like they might be related, but I'm not sure if this is a duplicate or a separate issue.

**Comment by shedatc** [comment]
It looks like I face this issue with el-get 5.1.9e4f1fa on Emacs 24.4.1. My .loaddefs.el contains MD5 hashes where time structures seems to be expected by update-directory-autoloads. Here is a snippet of my .loaddefs.el:

    ;;;### (autoloads nil "el-get/el-get-bundle" "../../../../../.emacs.d/el-get/el-get/el-get-bundle.el"
    ;;;;;;  "5d60bc715094fdbf95965c40aebf6111")
    ;;; Generated autoloads from ../../../../../.emacs.d/el-get/el-get/el-get-bundle.el

Any hint on what can be done do fix or workaround this?

**Comment by npostavs** [comment]
You can try `M-: (el-get-invalidate-autoloads)` which will totally regenerate all the autoloads from scratch.

Have you put things in non-standard places? It looks like more than the normal amount of `../`

**Comment by shedatc** [comment]
The call to el-get-invalidate-autoloads didn't change the fact that MD5
checksums were set in .loaddefs.el. The amount of "../" is due to my
~/.emacs.d being a symlink to somewhere else.

  Sheda

**Comment by npostavs** [comment]
> ~/.emacs.d being a symlink to somewhere else.

Aha. It seems having `.loaddefs.el` opened via the true name during autoload generation causes the md5 stuff.

```ShellSession
$ ls -l .emacs.d
lrwxrwxrwx 1 etest etest 8 Mar  9 20:03 .emacs.d -> emacs-d/
$ emacs -batch -Q -L emacs-d/el-get/el-get/ -l el-get --visit=emacs-d/el-get/.loaddefs.el -f el-get-invalidate-autoloads
el-get: updating autoloads for el-get
Wrote /home/etest/.emacs.d/el-get/.loaddefs.el
~/.emacs.d/el-get/.loaddefs.el and /home/etest/emacs-d/el-get/.loaddefs.el are the same file
File .loaddefs.el changed on disk.  Reread from disk? (yes or no) yes
Generating autoloads for ../../.emacs.d/el-get/el-get/el-get-autoloading.el...
...
~/.emacs.d/el-get/.loaddefs.el and /home/etest/emacs-d/el-get/.loaddefs.el are the same file
Generating autoloads for ../../.emacs.d/el-get/el-get/el-get-bundle.el...done
...
Generating autoloads for ../../.emacs.d/el-get/el-get/el-get-list-packages.el...
~/.emacs.d/el-get/.loaddefs.el and /home/etest/emacs-d/el-get/.loaddefs.el are the same file
Generating autoloads for ../../.emacs.d/el-get/el-get/el-get-list-packages.el...done
...
Generating autoloads for ../../.emacs.d/el-get/el-get/el-get.el...
~/.emacs.d/el-get/.loaddefs.el and /home/etest/emacs-d/el-get/.loaddefs.el are the same file
Generating autoloads for ../../.emacs.d/el-get/el-get/el-get.el...done
Saving file /home/etest/emacs-d/el-get/.loaddefs.el...
Wrote /home/etest/emacs-d/el-get/.loaddefs.el
(No changes need to be saved)
el-get: byte-compiling autoload file
Wrote /home/etest/.emacs.d/el-get/.loaddefs.elc
$ grep -E '[0-9a-f]{32}' emacs-d/el-get/.loaddefs.el
;;;;;;  "08fc70d24fc2dffafa39bf9f7869ccb5")
;;;;;;  "5d60bc715094fdbf95965c40aebf6111")
;;;;;;  "07f410ec5bb8851a065841ab0d1b9875")
$ emacs -batch -Q -L emacs-d/el-get/el-get/ -l el-get -f el-get-invalidate-autoloads
el-get: updating autoloads for el-get
Wrote /home/etest/.emacs.d/el-get/.loaddefs.el
Generating autoloads for el-get/el-get-autoloading.el...
...
Generating autoloads for el-get/el-get.el...done
Saving file /home/etest/.emacs.d/el-get/.loaddefs.el...
Wrote /home/etest/.emacs.d/el-get/.loaddefs.el
(No changes need to be saved)
el-get: byte-compiling autoload file
Wrote /home/etest/.emacs.d/el-get/.loaddefs.elc
$ grep -E '[0-9a-f]{32}' emacs-d/el-get/.loaddefs.el
```

**Comment by shedatc** [comment]
I'm unable to reproduce your test:

$ ls -ld .emacs.d
lrwxrwxrwx 1 stephaner stephaner 43 Feb 18 17:04 .emacs.d ->
/home/stephaner/ens/files/emacs/dot.emacs.d
$ emacs -batch -Q -L ens/files/emacs/dot.emacs.d/el-get/el-get -l el-get
--visit=ens/files/emacs/dot.emacs.d/el-get/.loaddefs.el -f
el-get-invalidate-autoloads; grep -E '[0-9a-f]{32}'
ens/files/emacs/dot.emacs.d/el-get/.loaddefs.el | wc -l
...
Wrote /home/stephaner/.emacs.d/el-get/.loaddefs.elc
46
$ emacs -batch -Q -L ens/files/emacs/dot.emacs.d/el-get/el-get -l el-get -f
el-get-invalidate-autoloads; grep -E '[0-9a-f]{32}'
ens/files/emacs/dot.emacs.d/el-get/.loaddefs.el | wc -l
...
Wrote /home/stephaner/.emacs.d/el-get/.loaddefs.elc
46

And when I run el-get-invalidate-autoloads from my standard session (i.e.,
not with -batch), it automatically visit the .loaddefs.el buffer (this
behaviour seems to comes from el-get-update-autoloads).

What did I miss?

**Comment by npostavs** [comment]
> What did I miss?

Dang, thought we'd found it. The only remaining difference I can see is packages installed. Can you try that test again with a fresh doc.emacs.d, installing only el-get?

**Comment by shedatc** [comment]
​Here is what I've done:​

$ ls -ld .t*-emacs*
-rw------- 1 stephaner stephaner    0 Mar 12 17:54 .t-emacs.orig
lrwxrwxrwx 1 stephaner stephaner   10 Mar 12 17:59 .t2-emacs.d -> .t-emacs.d
-rw------- 1 stephaner stephaner   44 Mar 12 17:59 .t-emacs
drwx------ 2 stephaner stephaner 4.0K Mar 12 17:59 .t-emacs.d
$ cat .t-emacs
(setq user-emacs-directory "~/.t2-emacs.d")
$ emacs -Q -l ~/.t-emacs

​Then, from emacs, evaluated the elisp necessary to install el-get:
​
(url-retrieve
 "https://raw.githubusercontent.com/dimitri/el-get/master/el-get-install.el"
 (lambda (s)
   (goto-char (point-max))
   (eval-print-last-sexp)))

​And (el-get-invalidate-autoloads). ​The resulting .loaddefs.el do not
contains MD5 checksums:

​$ grep -E '[0-9a-f]{32}'  ~/.t-emacs.d/el-get/.loaddefs.el
$ echo $?
1
$ head -n 20 ~/.t-emacs.d/el-get/.loaddefs.el
;;; .loaddefs.el --- automatically extracted autoloads
;;
;;; Code:



;;;### (autoloads (el-get el-get-self-checksum el-get-checksum
el-get-make-recipes
;;;;;;  el-get-cd el-get-reinstall el-get-remove el-get-self-update
;;;;;;  el-get-update-packages-of-type el-get-update-all el-get-update
;;;;;;  el-get-install el-get-version) "el-get/el-get" "el-get/el-get.el"
;;;;;;  (21761 50780 371864 505000))
;;; Generated autoloads from el-get/el-get.el

(autoload 'el-get-version "el-get/el-get" "\
Message the current el-get version

\(fn)" t nil)

(autoload 'el-get-install "el-get/el-get" "\
Cause the named PACKAGE to be installed after all of its
dependencies (if any).

​So, in itself, the use of symlinks don't seems to trigger the use of MD5
checksums.​

Sheda

**Comment by npostavs** [comment]
> ​So, in itself, the use of symlinks don't seems to trigger the use of MD5 checksums.​

Hmm, I tried also with a more deeply nested emacs-d, but that doesn't seem to trigger it either. Can you post your .status.el?

**Comment by shedatc** [comment]
Here it is.

**Comment by npostavs** [comment]
> Here it is.

It doesn't seem to have shown up.

**Comment by shedatc** [comment]
The attachment was probably stripped. Here it is (inline):

((apel status "installed" recipe
             (:name apel :website "
http://www.kanji.zinbun.kyoto-u.ac.jp/~tomo/elisp/APEL/" :description "APEL
(A Portable Emacs Library) is a library to support to write portable Emacs
Lisp programs." :type github :pkgname "wanderlust/apel" :build
                            (mapcar
                             (lambda
                                 (target)
                                 (list el-get-emacs
                                             (split-string "-batch -q
-no-site-file -l APEL-MK -f")
                                             target "prefix" "site-lisp"
"site-lisp"))
                             '("compile-apel" "install-apel"))
                            :load-path
                            ("site-lisp/apel" "site-lisp/emu")))
 (bbdb status "installed" recipe
             (:name bbdb :website "http://bbdb.sourceforge.net/"
:description "The Insidious Big Brother Database (BBDB) is a contact
management utility." :type git :url "git://git.savannah.nongnu.org/bbdb.git"
:load-path
                            ("./lisp")
                            :build
                            `("./autogen.sh" "./configure" "make")
                            :features bbdb-loaddefs :autoloads nil :info
"doc"))
 (bm status "installed" recipe
         (:name bm :pkgname "joodland/bm" :website "
http://joodland.github.com/bm/" :type github :description "Visible,
persistent, buffer local, bookmarks"))
 (el-get status "installed" recipe
                 (:name el-get :website "
https://github.com/dimitri/el-get#readme" :description "Manage the external
elisp bits and pieces you depend upon." :type github :branch "master"
:pkgname "dimitri/el-get" :info "." :compile
                                ("el-get.*\\.el$" "methods/")
                                :features el-get :post-init
                                (when
                                        (memq 'el-get
                                                    (bound-and-true-p
package-activated-list))
                                    (message "Deleting melpa bootstrap
el-get")
                                    (unless package--initialized
                                        (package-initialize t))
                                    (when
                                            (package-installed-p 'el-get)
                                        (let
                                                ((feats
                                                    (delete-dups

 (el-get-package-features

(el-get-elpa-package-directory 'el-get)))))
                                            (el-get-elpa-delete-package
'el-get)
                                            (dolist
                                                    (feat feats)
                                                (unload-feature feat t))))
                                    (require 'el-get))))
 (emacs-w3m status "installed" recipe
                        (:name emacs-w3m :description "A simple Emacs
interface to w3m" :type cvs :website "http://emacs-w3m.namazu.org/" :module
"emacs-w3m" :url ":pserver:anonymous@cvs.namazu.org:/storage/cvsroot" :build
                                     `("autoconf"
                                         ("./configure" ,(format
"--with-emacs=%s" el-get-emacs))
                                         "make")
                                     :build/windows-nt
                                     (("sh" "./autogen.sh")
                                        ("sh" "./configure")
                                        "make")
                                     :info "doc"))
 (flim status "installed" recipe
             (:name flim :description "A library to provide basic features
about message representation or encoding" :depends apel :type github
:branch "flim-1_14-wl" :pkgname "wanderlust/flim" :build
                            (mapcar
                             (lambda
                                 (target)
                                 (list el-get-emacs
                                             (mapcar
                                                (lambda
                                                    (pkg)
                                                    (mapcar
                                                     (lambda
                                                         (d)
                                                         `("-L" ,d))
                                                     (el-get-load-path
pkg)))
                                                '("apel"))
                                             (split-string "-batch -q
-no-site-file -l FLIM-MK -f")
                                             target "prefix" "site-lisp"
"site-lisp"))
                             '("compile-flim" "install-flim"))
                            :load-path
                            ("site-lisp/flim")))
 (markdown-mode status "installed" recipe
                                (:name markdown-mode :description "Major
mode to edit Markdown files in Emacs" :website "
http://jblevins.org/projects/markdown-mode/" :type git :url "git://
jblevins.org/git/markdown-mode.git" :prepare
                                             (add-to-list 'auto-mode-alist

'("\\.\\(md\\|mdown\\|markdown\\)\\'" . markdown-mode))))
 (pretty-mode status "installed" recipe
                            (:name pretty-mode :description "Redisplay
parts of the buffer as pretty symbols" :type emacswiki :features
"pretty-mode"))
 (semi status "installed" recipe
             (:name semi :description "SEMI is a library to provide MIME
feature for GNU Emacs." :depends flim :type github :branch "semi-1_14-wl"
:pkgname "wanderlust/semi" :build
                            (mapcar
                             (lambda
                                 (target)
                                 (list el-get-emacs
                                             (mapcar
                                                (lambda
                                                    (pkg)
                                                    (mapcar
                                                     (lambda
                                                         (d)
                                                         `("-L" ,d))
                                                     (el-get-load-path
pkg)))
                                                '("apel" "flim"))
                                             (split-string "-batch -q
-no-site-file -l SEMI-MK -f")
                                             target "prefix" "site-lisp"
"site-lisp"))
                             '("compile-semi" "install-semi"))
                            :load-path
                            ("site-lisp/semi/")))
 (wanderlust status "installed" recipe
                         (:name wanderlust :description "Wanderlust
bootstrap." :depends semi :type github :pkgname "wanderlust/wanderlust"
:build
                                        (mapcar
                                         (lambda
                                             (target-and-dirs)
                                             (list el-get-emacs
                                                         (mapcar
                                                            (lambda
                                                                (pkg)
                                                                (mapcar
                                                                 (lambda
                                                                     (d)
                                                                     `("-L"
,d))

 (el-get-load-path pkg)))
                                                            (append
                                                             '("apel"
"flim" "semi")
                                                             (when

 (el-get-package-exists-p "bbdb")
                                                                 (list
"bbdb"))))
                                                         "--eval"

 (el-get-print-to-string
                                                            '(progn
                                                                 (setq
wl-install-utils t)
                                                                 (setq
wl-info-lang "en")
                                                                 (setq
wl-news-lang "en")))
                                                         (split-string
"-batch -q -no-site-file -l WL-MK -f")
                                                         target-and-dirs))
                                         '(("wl-texinfo-format" "doc")
                                             ("compile-wl-package"
"site-lisp" "icons")
                                             ("install-wl-package"
"site-lisp" "icons")))
                                        :info "doc/wl.info" :load-path
                                        ("site-lisp/wl" "utils")
                                        :post-init
                                        (progn
                                            (setq wl-icon-directory
                                                        (expand-file-name
"etc/icons" default-directory))))))

**Comment by npostavs** [comment]
So I'm still not able to reproduce your results. #2125 should fix the visited-via-truename-problem I found earlier. If that doesn't also solve your problem, post the `*trace-output*` buffer after evaluating:
```elisp
(require 'trace)
(mapc #'trace-function-background
      '( ;;make-autoload
        autoload-find-generated-file
        autoload-generated-file
        autoload-read-section-header
        ;;autoload-print-form
        autoload-rubric
        autoload-ensure-default-file
        autoload-insert-section-header
        autoload-find-file
        autoload-file-load-name
        generate-file-autoloads
        autoload--setup-output
        autoload--print-cookie-text
        autoload-generate-file-autoloads
        autoload-save-buffers
        update-file-autoloads
        autoload-find-destination
        autoload-remove-section
        update-directory-autoloads
        update-autoloads-from-directories
        batch-update-autoloads))
(el-get-invalidate-autoloads)
```

**Comment by shedatc** [comment]
I replaced el-get-autoloading.el with the on found here: https://raw.githubusercontent.com/npostavs/el-get/a9ad872de9218d02a4d56970eea11b14ab4368c1/el-get-autoloading.el

It doesn't solve my problem. Here is the requested trace output: http://s000.tinyupload.com/?file_id=90641875488802788668

**Comment by npostavs** [comment]
> Here is the requested trace output

Thanks, I think can see the problem. Do you have `find-file-visit-truename` set to `t` in your config? I've added another commit to #2125 to deal with this.

Although, maybe there's also something else because you reported problems even with `emacs -batch -Q`...

> I replaced el-get-autoloading.el

Did you also take care of the stale elc?

---

```ShellSession
$ emacs -batch -Q -L a/b/c/emacs-d/el-get/el-get/ -l el-get --eval '(setq find-file-visit-truename t)'  -f el-get-invalidate-autoloads
el-get: updating autoloads for apel
...
~/.emacs.d/el-get/.loaddefs.el and /home/etest/a/b/c/emacs-d/el-get/.loaddefs.el are the same file
Wrong type argument: listp, "8e5644b079ecfef02aa1caf5969e29f8"
```

**Comment by npostavs** [comment]
I've merge #2125, hopefully this fixes all problems, please report if otherwise.
