### ISSUE TITLE
Installing package from ELPA pulls in dependencies twice

### ISSUE THREAD

**Issue by kini** [dimitri/el-get#1790]
Installing `flycheck-haskell` from ELPA seems to have installed `dash-2.7.0`, `epl-0.7`, `f-0.11.0`, `flycheck-0.19`, `haskell-mode-13.7`, `pkg-info-0.5`, and `s-1.9.0` into `~/.emacs.d/elpa/` but it has _also_ installed `dash`, `epl`, `f`, `flycheck`, `haskell-mode`, `pkg-info`, and `s` into `~/.emacs.d/el-get` simultaneously! There is also a symlink from `~/.emacs.d/el-get/flycheck-haskell` to `../elpa/flycheck-haskell-0.4`.

The problem is that now I have all these old versions of packages getting loaded. I used to have the latest version of haskell-mode from github (the one in `~/.emacs.d/el-get/haskell-mode`), but now Emacs is loading the version from `~/.emacs.d/elpa`, which is almost 1 year old now.

The relevant section of my `~/.emacs.d/init.el` looks like this:

``` elisp
;; el-get setup
(add-to-list 'load-path "~/.emacs.d/el-get/el-get")

(unless (require 'el-get nil 'noerror)
  (with-current-buffer
      (url-retrieve-synchronously
       "https://raw.github.com/dimitri/el-get/master/el-get-install.el")
    (goto-char (point-max))
    (eval-print-last-sexp)))

(add-to-list 'el-get-recipe-path "~/.emacs.d/el-get-user/recipes")
(el-get 'sync)

;; ELPA setup
(require 'package)
(add-to-list 'package-archives
         '("marmalade" . "http://marmalade-repo.org/packages/"))
(package-initialize)

(require 'el-get-elpa)
;; Build the El-Get copy of the package.el packages if we have not
;; built it before.  Will have to look into updating later ...
(unless (file-directory-p el-get-recipe-path-elpa)
  (el-get-elpa-build-local-recipes))
```

**Comment by aspiers** [comment]
What's the latest thinking on this problem?  Presumably I am not the only person for whom this is causing problems?  Are people switching to Quelpa, or is there some newer fix or workaround in `el-get`?  Even if this is still an unsolved problem, it would be really helpful to at least document it in the manual, e.g. suggest one or two approaches to configuring el-get, and set expectations of what will and won't work.

**Comment by npostavs** [comment]
I think this has been solved by #1798, nobody has reported otherwise.

**Comment by aspiers** [comment]
@npostavs I don't think so - at very least I occasionally get the same sort of problems with `flycheck` reported by @kini above, but the comments following his mention of that also suggest to me that the status quo is not a complete solution.

**Comment by npostavs** [comment]
I added 5b758fdff13a94fdc1449f0b111c925aaa0da9e3 to fix that, and as far as I know it worked.

**Comment by aspiers** [comment]
My version of `el-get` certainly includes that commit, and I'm still seeing this in the `*Warnings*` buffer on startup:

```
Warning (emacs): Unable to activate package `flycheck-package'.
Required package `flycheck-0.22' is unavailable
```

**Comment by aspiers** [comment]
To clarify, I installed both `flycheck` and `flycheck-package` via `el-get`; however [`flycheck-package` from MELPA has a dependency on `flycheck-0.22`](https://melpa.org/#/flycheck-package) which is not satisfied by `el-get`.  So whilst your commit does indeed prevent dependencies from being pulled in twice, the larger problem of packages installed from `el-get` recipes and *ELPA peacefully coexisting is not yet solved.  And it's that larger problem which I was referring to in https://github.com/dimitri/el-get/issues/1790#issuecomment-157351200.

**Comment by aspiers** [comment]
One obvious thought arising from this is that `el-get` should be able to track package versions.  If it did that then it could ensure that the `package.el` ecosystem knows that there is a `flycheck >= 0.22` installed.  Is there any reason why `el-get` doesn't track versions?

**Comment by npostavs** [comment]
> To clarify, I installed both flycheck and flycheck-package via el-get

What is `flycheck-package`, and how can you install it via `el-get` (I don't see any `flycheck-package.rcp`)?

> Is there any reason why el-get doesn't track versions?

There's no particular reason beyond the fact that nobody has implemented it yet. It can be a bit tricky because not all packages even have version numbers.

**Comment by vyp** [comment]
@aspiers already linked to it, but to clarify, this is flycheck-package: https://github.com/purcell/flycheck-package. Even if there's no recipe in this repository, one can still install arbitrary elisp by providing a recipe themselves (as I'm sure you already know, but for some reason you still asked).

**Comment by DarwinAwardWinner** [comment]
> Is there any reason why el-get doesn't track versions?

I explained the reason that el-get doesn't track versions as a side note in a different context: https://github.com/dimitri/el-get/issues/2279

In short, the lack of version-awareness is deeply rooted in el-get's origin as a way to easily track the master branches of packages that were not yet packaged, or for which the version in package.el was out of date. Changing it would require major refactoring.

I don't know if there's a general solution to this problem that doesn't involve making el-get version-aware. There is a partial solution for some cases, however. If none of the recipes in your `el-get-sources` is a dependency of an elpa-type recipe in `el-get-sources`, then all you have to do is make sure your elpa-type recipes don't declare any dependencies at all, and elpa itself will handle all the dependencies just fine. (Admittedly, this is not an intuitive solution.) However, if you try to use el-get to install package X through elpa and package Y that is a dependency of X via some other method, then elpa will also install package Y, and you can run into the problem described in this issue, where the el-get copy of package Y overrides the elpa copy but package X wants the elpa copy, leading to an error.

For this reason, I've pretty much avoided mixing el-get and elpa as much as possible in my emacs config. These days, I install as much as possible via elpa, and then install the rest via el-get.

**Comment by npostavs** [comment]
> Even if there's no recipe in this repository, one can still install arbitrary elisp by providing a recipe themselves (as I'm sure you already know, but for some reason you still asked).

Yes, but then I need to see what recipe is being used, otherwise I have no idea what "install via el-get" means.

**Comment by aspiers** [comment]
@npostavs wrote:
> What is flycheck-package, and how can you install it via el-get (I don't see any flycheck-package.rcp)?

`el-get` supports installing from ELPA repositories, and I have MELPA configured as one of my ELPA repositories, so in this case it comes from https://melpa.org/#/flycheck-package via a recipe auto-generated by `M-x el-get-elpa-build-local-recipes`.

> @vyp wrote:
> > Even if there's no recipe in this repository, one can still install arbitrary elisp by providing a recipe themselves (as I'm sure you already know, but for some reason you still asked).
>
> Yes, but then I need to see what recipe is being used, otherwise I have no idea what "install via el-get" means.

Here it is:

```
(:name flycheck-package
       :auto-generated t
       :type elpa
       :description "A Flycheck checker for elisp package authors"
       :repo nil
       :depends
       (cl-lib flycheck)
       :minimum-emacs-version
       (24))
```

@DarwinAwardWinner Thanks a lot, that's very useful information.  I was also approaching a similar conclusion about installing as much as possible via elpa (which handles versions accurately), and then using `el-get` only for stuff where I really want the bleeding edge.

**Comment by vyp** [comment]
@npostavs oh sorry I misunderstood.

**Comment by npostavs** [comment]
Okay, so it seems that this problem shows up only if you have a `(package-initialize)` call before your `(el-get 'sync)` call (note that recent Emacs automatically insert `(package-initialize)` at the top of your init file if it's not there already). @aspiers can you confirm?

I think the solution is just to add a note in the doc advising to put `(package-initialize)` after `(el-get 'sync)`.

**Comment by DarwinAwardWinner** [comment]
I don't know if that's a real solution, or if it's just changing which version of the package Emacs will prefer in such a way that happens to work for a specific test case.

**Comment by npostavs** [comment]
> I don't know if that's a real solution, or if it's just changing which version of the package Emacs will prefer in such a way that happens to work for a specific test case.

It's letting the el-get installed package be preferred over package.el's.

**Comment by aspiers** [comment]
> Okay, so it seems that this problem shows up only if you have a (package-initialize) call before your (el-get 'sync) call (note that recent Emacs automatically insert (package-initialize) at the top of your init file if it's not there already). @aspiers can you confirm?

Actually I have settled on putting `(package-initialize 'no-activate)` before `(el-get 'sync)`.  This ensures that `package-archive-contents` is populated (which I need in order to determine which ELPA packages are missing from the local install, if any) without activating ELPA packages by bypassing `el-get`.  But in cases like `flycheck-package` this is still problematic as described.

> I think the solution is just to add a note in the doc advising to put (package-initialize) after (el-get 'sync).

I'm not sure how that would help?  `flycheck` would still get loaded from the `el-get` recipe, and `flycheck` would still get loaded by `el-get` from the auto-generated MELPA recipe, so its dependency on a particular version of `flycheck` would still fail.

What I really want is to adopt @DarwinAwardWinner's suggestion:

> These days, I install as much as possible via elpa, and then install the rest via el-get

But I'm not sure what is the best way of achieving that.  Maybe by not installing the elpa packages through `el-get`'s elpa backend but by using `(package-install ...)`?  Or using `req-package`'s `:loader` keyword?  Or `(el-get-bundle elpa:...)`?

**Comment by npostavs** [comment]
> Actually I have settled on putting (package-initialize 'no-activate) before (el-get 'sync). This ensures that package-archive-contents is populated (which I need in order to determine which ELPA packages are missing from the local install, if any) without activating ELPA packages by bypassing el-get. But in cases like flycheck-package this is still problematic as described.

Hmm, I think that should work. Can you post enough of your config to reproduce the problem?

> I'm not sure how that would help? flycheck would still get loaded from the el-get recipe, and flycheck would still get loaded by el-get from the auto-generated MELPA recipe, so its dependency on a particular version of flycheck would still fail.

I'm a bit confused now, `flycheck` is *also* an auto-generated MELPA recipe? You're not using https://github.com/dimitri/el-get/blob/master/recipes/flycheck.rcp?

**Comment by aspiers** [comment]
> Hmm, I think that should work. Can you post enough of your config to reproduce the problem?

I probably won't have time to write a minimal test case, but:

- https://github.com/aspiers/emacs/blob/master/.emacs.d/init.d/as-elpa.el
- https://github.com/aspiers/emacs/blob/master/.emacs.d/init.d/as-el-get.el

> I'm a bit confused now, flycheck is also an auto-generated MELPA recipe? You're not using https://github.com/dimitri/el-get/blob/master/recipes/flycheck.rcp?

Sorry, it was a typo :)  Yes I'm using https://github.com/dimitri/el-get/blob/master/recipes/flycheck.rcp - I meant that flycheck-*package* would still get loaded by el-get from the auto-generated MELPA recipe.
