### ISSUE TITLE
Merging bundle-el or similar functionality into el-get core?

### ISSUE THREAD

**Issue by priyadarshan** [dimitri/el-get#1967]
I wanted to point out to `el-get` maintainers the `bundle` wrapper (https://github.com/tarao/bundle-el). I have been using it for some time and found it synergistic to `el-get`, simple to use and with a syntax in tune with `el-get` spirit.

Possibly within a future milestone, would it make sense at all to merge `bundle-el` (if the maintainer agrees), or incorporate a similar feature into `el-get` core?

**Comment by npostavs** [comment]
Done in #1976.
