### ISSUE TITLE
Feature request: pushing new recipes

### ISSUE THREAD

**Issue by Pitometsu** [dimitri/el-get#2074]
Is there possible to push new recipes to repository directly from emacs via el-get without interacting with git/github? It will be much easer for newbies. Thank you.

**Comment by npostavs** [comment]
You need write access to push to the repository, and presumably those with write access aren't newbies...

It's possible to interface with git from Emacs, e.g. I use [magit].

For interfacing with github there's [magit-gh-pulls], but I don't use it, and I'm not even sure if it's currently functional.
[magit-gh-pulls]: https://github.com/sigma/magit-gh-pulls
[magit]: https://github.com/magit/magit/
