### ISSUE TITLE
Can't deal with ;;;###autoload statements requiring multiple files

### ISSUE THREAD

**Issue by zilti** [dimitri/el-get#2075]
El-get is broken I guess. I have the following recipe and it doesn't work anymore:

```emacs-lisp
(el-get-bundle powerline
:description "A Powerline rewrite."
:type hg
:url "https://zilti@bitbucket.org/zilti/powerline"
:features powerline
:compile ("powerline.el" "powerline-themes.el" "powerline-separators.el" "powerline-extensions.el"))
```

`Cannot open load file: file or directory not found, powerline-themes`.

I'm running Emacs 24.4. The only way to make it work is to manually `eval-buffer` each of those files and then evaluating the whole form again.

**Comment by npostavs** [comment]
It's a basically the same problem as [2056]: el-get evaluates the autoload before setting up the load-path. You could say `:autoloads nil` but then you don't get the powerline setup automagically.

I guess the only real solution is to have a per-package autoload files.

[2056]: https://github.com/dimitri/el-get/issues/2056#issuecomment-68664576

**Comment by npostavs** [comment]
> You could say :autoloads nil but then you don't get the powerline setup automagically.

Uh, actually scratch that. `:autoloads nil` is a good solution for this package. I somehow thought the `defpowerline` should change the modeline, but obviously it doesn't.

By the way, `:features powerline` already does `(require 'powerline)` so you could remove it from the installations instructions, or remove `:features` from the recipe.
