### ISSUE TITLE
what should I do after I installed el-get

### ISSUE THREAD

**Issue by allen0125** [dimitri/el-get#2108]
I use the basic setup installed el-get into my emacs(add 

```elisp
(add-to-list 'load-path "~/.emacs.d/el-get/el-get")

(unless (require 'el-get nil 'noerror)
  (with-current-buffer
      (url-retrieve-synchronously
       "https://raw.githubusercontent.com/dimitri/el-get/master/el-get-install.el")
    (goto-char (point-max))
    (eval-print-last-sexp)))

(add-to-list 'el-get-recipe-path "~/.emacs.d/el-get-user/recipes")
(el-get 'sync)
```

 into .emacs)

Then I use M-x el-get-install install nyan-mode , M-x el-get-init nyan-mode.
restart emacs But the nyan-mode doesn't exist. what should I do when installed the package?

**Comment by npostavs** [comment]
> But the nyan-mode doesn't exist.

What do you mean exactly by "doesn't exist"? I think you have to do `M-x nyan-mode` to start it.

**Comment by allen0125** [comment]
It's mean how to load nyan-mode after I install it when Emacs start? I hava to do M-x nyanmode everytimes?

**Comment by npostavs** [comment]
You can add `(nyan-mode +1)` after `(el-get 'sync)` instead.

**Comment by allen0125** [comment]
Thanks for your help , It's very helpful for me !
