### ISSUE TITLE
invalid evil git repo

### ISSUE THREAD

**Issue by felixSchl** [dimitri/el-get#2123]
I might be wrong - I am just starting out with emacs - but I seem unable to install `evil` using the recipe provided in this repo. Changing the url from `git://` to `http://` seems to fix it.

**Comment by npostavs** [comment]
What goes wrong? According to http://gitorious.org/evil/pages/Home `git://` is correct. Can you clone the repository from the command line?

There have been quite a few cases of people needing to change git protocol, with this new issue we have almost every possible transition:

| from/to | http  | https | git  |
|---------|-------|-------|------|
| http    |       | #604  | #698 |
| https   | #1452 |       | #698 |
| git     | #2123 |       |      |

Just missing a report from someone that needed to replace git with https. :)

This suggests that perhaps `el-get-github-default-url-type` should somehow be generalised to `:type git`.


[1452]: https://github.com/dimitri/el-get/pull/1452#issuecomment-28957830

**Comment by felixSchl** [comment]
`git clone git://gitorious.org/evil/evil.git` fails with:

```
Cloning into 'evil'...
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by npostavs** [comment]
hmm, I get the same results from 2 different computers, so I've changed the url to http.

Maybe you can let the authors know that the instructions they have are wrong...
