### ISSUE TITLE
color-theme is not install because GNU mirror is down

### ISSUE THREAD

**Issue by deterok** [dimitri/el-get#2177]
http://download.savannah.gnu.org/releases/color-theme/color-theme-6.6.0.tar.gz is redirect to public.p-knowledge.co.jp (http://downforeveryoneorjustme.com/public.p-knowledge.co.jp)

public.p-knowledge.co.jp is down for now.

Maybe replace the mirror?

**Comment by npostavs** [comment]
el-get doesn't control which mirror gets selected, so I don't know what we can do about it.

It works for me, because a different mirror gets selected (I guess it's based on IP geolocation).
