### ISSUE TITLE
el-get fails to install with: "error in process filter: End of buffer"

### ISSUE THREAD

**Issue by terry3** [dimitri/el-get#2198]
Windows 7
emacs 24.3.1
el-get 4.0.7.20f5d34

run log(el-get-verbose t):
```
el-get-install cscope: (cscope)
el-get-install-next-packages: cscope
Contacting host: raw.github.com:443
Opening TLS connection to `raw.github.com'...
Opening TLS connection with `gnutls-cli --insecure -p 443 raw.github.com'...failed
Opening TLS connection with `sc --insecure -p 443 raw.github.com --protocols ssl3'...failed
Opening TLS connection with `openssl s_client -connect raw.github.com:443 -no_ssl2 -ign_eof'...done
Opening TLS connection to `raw.github.com'...done
el-get install cscope
error in process filter: apply: End of buffer
error in process filter: End of buffer
```

**Comment by npostavs** [comment]
> el-get 4.0.7.20f5d34

This is a very old version of el-get, a current release would be 5.1.something

Also, it looks like you're using an external tool to handle TLS/SSL, using gnutls dlls as described in https://github.com/dimitri/el-get/wiki/Installation-on-Windows would be more reliable.

**Comment by terry3** [comment]
> Also, it looks like you're using an external tool to handle TLS/SSL, using gnutls dlls as described in > https://github.com/dimitri/el-get/wiki/Installation-on-Windows would be more reliable.

after replace the dlls, the above error does not appear. THANKS npostavs !
bty, does 'el-get-self-update can not update el-get from old version  to the latest one?

**Comment by npostavs** [comment]
> 'el-get-self-update can not update el-get from old version to the latest one?

Um, I guess you have to change to the master branch by adding a recipe override to `el-get-sources` first like `(:name el-get :branch "master")`.

@dimitri: was there an official upgrade path from 4.stable to the "rolling release"?

**Comment by dimitri** [comment]
See http://tapoueh.org/blog/2014/01/11-el-get-rolling-release

**Comment by terry3** [comment]
Thank you all.
