### ISSUE TITLE
pdf-tools recipe does not work

### ISSUE THREAD

**Issue by vyp** [dimitri/el-get#2207]
It complains about no let-alist. Installing manually (`package-install-file`) as instructed at https://github.com/politza/pdf-tools works. Doing:

    (el-get-bundle let-alist)
    (el-get-bundle pdf-tools)

however, works too. I'm not sure if the recipe should have `:depends (let-alist)`, and I'm not sure how to check for that. [Link to the recipe](https://github.com/dimitri/el-get/blob/master/recipes/pdf-tools.rcp).

As I understood it, let-alist was already a built in package, so maybe this is just me. Does the recipe work for you?

**Comment by vyp** [comment]
On emacs 24.5.1.

**Comment by npostavs** [comment]
> I'm not sure if the recipe should have :depends (let-alist), and I'm not sure how to check for that.

Well the [`Package-Requires:` header][1] is usually a good guide to follow (occasionally, repos are divided into multiple ELPA packages, so it's not 100% certain). Looks like you might need `:depends (let-alist tablist)`, and also `:minimum-emacs-version "24.3"`.

> As I understood it, let-alist was already a built in package,

It's builtin on Emacs 25.

[1]: https://github.com/politza/pdf-tools/blob/971ffb85bbce30af257c3c4824e292cb5a00c31d/lisp/pdf-tools.el#L9

**Comment by vyp** [comment]
Thanks for the information. tablist was there but removed #2112.

**Comment by vyp** [comment]
So which version of emacs does el-get target? If 25 already has let-alist, then should the recipe include `:depends (let-alist)`?

**Comment by npostavs** [comment]
> tablist was there but removed

Ah, so that's indeed an example of what I said above:

> occasionally, repos are divided into multiple ELPA packages, so it's not 100% certain.

---

> So which version of emacs does el-get target? If 25 already has let-alist, then should the recipe include :depends (let-alist)?

el-get targets 23.4 and later. You should add `:depends (let-alist)`, the `let-alist` recipe has `:builtin "25.1"` so it won't be installed twice on Emacs 25. Actually, probably that should be changed to `:builtin "25.0.50"`, because nobody has 25.1 installed yet!
