### ISSUE TITLE
Trying to install packages: error doesn't provide enough information

### ISSUE THREAD

**Issue by uaalto** [dimitri/el-get#2226]
I'm trying to install go-related packages, but provided error messages don't allow me to try and figure out what's wrong with installation:

```
Package go-errcheck previously failed to install, removing it first.
el-get: updating autoloads for go-errcheck
el-get: byte-compiling autoload file
go-errcheck removed: This package has been removed successfully by el-get.
el-get remove go-errcheck
go-errcheck failed to install: (error el-get: :program argument cannot be nil)
el-get-installation-failed: el-get: :program argument cannot be nil
Quit [6 times]
Quit
```

The obvious possible issue that is not finding the `go` program has been discarded as a possible cause. Still, the error should be more informative, otherwise I'm stuck.

**Comment by npostavs** [comment]
yup, there were some places not using `el-get-executable-find`, which does actually give an error message that's actually comprehensible to someone who hasn't read the source code.

**Comment by uaalto** [comment]
Thank you!
