### ISSUE TITLE
Could :load-path be changed to append to the end of load-path?

### ISSUE THREAD

**Issue by jsyjr** [dimitri/el-get#2228]
I am trying to keep a "patched" directory at the front of my load-path.  el-get recipes that specify :load-path screw that up.  I know that cons-ing onto the front of a list is cheaper but we are only talking a small number of append operations on a relatively short list during emacs initialization.  So is there any logical reason that appending could not be to the end of load-path?  Perhaps a custom setting?

**Comment by DarwinAwardWinner** [comment]
Some packages have older versions that are bundled with Emacs (e.g. org-mode), so unless their load-path is prepended, the el-get installed version would not be used.

**Comment by jsyjr** [comment]
I found a way to satisfy my requirement.
