### ISSUE TITLE
autoloads problem

### ISSUE THREAD

**Issue by Pitometsu** [dimitri/el-get#2240]
![screenshot](http://i.imgur.com/VZkYVxC.png)
Expected: list of extracted autoloads
Actual: list empty

**Comment by npostavs** [comment]
What Emacs version? Is that the only package with this problem? Does regenerating the autoloads by evaluating `(el-get-invalidate-autoloads 'structured-haskell-mode)` fix it?

**Comment by Pitometsu** [comment]
```
hackbook% emacs -nw -Q -version
GNU Emacs 24.5.2
Copyright (C) 2015 Free Software Foundation, Inc.
GNU Emacs comes with ABSOLUTELY NO WARRANTY.
You may redistribute copies of Emacs
under the terms of the GNU General Public License.
For more information about these matters, see the file named COPYING.
```

**Comment by Pitometsu** [comment]
It may be related to #2241 because I had to restart package installation few times and .loaddefs.el may been corrupted.

**Comment by npostavs** [comment]
> .loaddefs.el may been corrupted.

You can evaluate `(el-get-invalidate-autoloads)` to regenerate it from scratch.

**Comment by Pitometsu** [comment]
@npostavs thanks, now it's ok, issue may be closed.
