### ISSUE TITLE
el-get-http fails with stacktrace when failing to connect to github through proxy

### ISSUE THREAD

**Issue by SamHasler** [dimitri/el-get#2247]
This is caused by a bug in emacs:

http://debbugs.gnu.org/cgi/bugreport.cgi?bug=11788

And using the patch there fixes it, but I still think el-get shouldn't be throwing an error/stacktrace. Putting this here in case anyone else using el-get on windows with a corporate proxy has the same problem.

```
Debugger entered--Lisp error: (error "could not fetch URL https://raw.github.com/tarao/evil-plugins/master/evil-mode-line.el: error http (503)")
  signal(error ("could not fetch URL https://raw.github.com/tarao/evil-plugins/master/evil-mode-line.el: error http (503)"))
  error("could not fetch URL https://raw.github.com/tarao/evil-plugins/master/evil-mode-line.el: error http (503)")
  el-get-http-retrieve-callback((:error (error http 503)) evil-mode-line "https://raw.github.com/tarao/evil-plugins/master/evil-mode-line.el" el-get-post-install "<MYPATH>/.emacs.d/el-get/evil-mode-line/evil-mode-line.el" nil)
  el-get-http-install(evil-mode-line "https://raw.github.com/tarao/evil-plugins/master/evil-mode-line.el" el-get-post-install)
```

```
(message (format "%s" url-proxy-services))
; => "((http . my-cntlm-proxy:3128) (https . my-cntlm-proxy:3128))"
```

This is the recipie I'm using:
```
(:name evil-mode-line
       :website "https://github.com/tarao/evil-plugins"
       :description "state indicator at the beginning of the mode line and
       changes the mode line color for each state."
       :type http
       :url "https://raw.github.com/tarao/evil-plugins/master/evil-mode-line.el"
;       :url "https://raw.githubusercontent.com/tarao/evil-plugins/master/evil-mode-line.el"
       :depends evil)
```

If I remove the url-proxy-services setting I get the following messages but no stacktrace:
```
Contacting host: raw.githubusercontent.com:443
open-network-stream: make client process failed: Connection timed out, :name, raw.github.com, :buffer, #<killed buffer>, :host, raw.github.com, :service, 443, :nowait, nil
```

**Comment by npostavs** [comment]
> I still think el-get shouldn't be throwing an error/stacktrace.

How are you calling the `el-get-install`? e.g. if you `C-x C-e` after `(let ((el-get-default-process-sync 'sync)) (el-get-install 'evil-mode-line))` you will get a backtrace because `C-x C-e` temporarily enables `debug-on-error`. If you do a non-synchronous install the error occurs after the temporary setting is gone so you don't get a backtrace.

**Comment by SamHasler** [comment]
I was doing M-x el-get-install RET evil-mode-line RET

**Comment by npostavs** [comment]
> I was doing M-x el-get-install RET evil-mode-line RET

Then I don't understand how you ended up with a backtrace unless you enabled `debug-on-error` yourself.

I tried tried to simulate your error by calling `error` from `el-get-http-retrieve-callback`, and I just got the error message, no backtrace.
```diff
@@ -30,6 +30,7 @@ (defun el-get-filename-from-url (url)
 
 (defun el-get-http-retrieve-callback (status package url post-install-fun &optional dest sources)
   "Callback function for `url-retrieve', store the emacs lisp file for the package."
+  (error "http will now fail!")
   (let ((err (plist-get status :error)))
     (when err (error (format "could not fetch URL %s: error %s %s"
                              url (car (cdr err)) (cdr (cdr err))))))
```

**Comment by sariya** [comment]
Hi There,

I get the same error, emacs 24.5.1 Mac OSX 10.9
I'm trying to install as the instructions on page. But repeatedly get the error:

`Debugger entered--Lisp error: (error "Could not create connection to raw.githubusercontent.com$`

I do not have package.el file too.
Please advise.

**Comment by npostavs** [comment]
> I'm trying to install as the instructions on page.

@sariya: If you mean installing el-get, that's quite a different, please open a new issue.

**Comment by sariya** [comment]
@npostavs Sorry.
