### ISSUE TITLE
install magit via el-get

### ISSUE THREAD

**Issue by romankrv** [dimitri/el-get#2251]
Hi all,
I try to install magit via el-get but have next log:

Error (el-get): while installing magit: el-get: make el-get could not build magit [make EMACSBIN=/u\
  sr/local/bin/emacs docs

How to fix it? Thanks

**Comment by npostavs** [comment]
Probably you don't have `makeinfo` installed. You can install it, or if you don't care to have texinfo manuals you can remove documentation building from the recipe by adding an entry to `el-get-sources`:

```elisp
 (:name magit
        :info nil
        :build (("touch" "lisp/magit-autoloads.el"))
        :build/berkeley-unix nil)
```

See also #2190, for a similar problem with slime.

**Comment by romankrv** [comment]
thanks for piece of advice.
