### ISSUE TITLE
el-get install dash.showed error

### ISSUE THREAD

**Issue by cndlhvn** [dimitri/el-get#2260]
Hello
How to remove error message?
Write "(el-get-bundle dash)" in "~/.emacs.d/init.el".
Open emacs.
And then el-get starts to install dash.
Finally el-get shows error message.

"""File error: Cannot open load file, dash"""
Of course, the installation is successful,but error message is showed
I don't know how to remove this error message.
thank you.

**Comment by npostavs** [comment]
> Write "(el-get-bundle dash)" in "~/.emacs.d/init.el".

You must have other things in "~/.emacs.d/init.el", can you post a minimal example?

**Comment by cndlhvn** [comment]
This is my fault.
My emacs environment is this.

CentOS .6.5
emacs 24.3

emacs-24.3 always prints error to install dash.
So I had upgrade the emacs to 24.5.
emacs24.5 doesn't show any error.
This problem was because I am using an older emacs version.

**Comment by npostavs** [comment]
I just tried `test/test-recipe-interactive.sh dash` with Emacs 24.3 and it succeeded.
