### ISSUE TITLE
Access to cloned directory from init

### ISSUE THREAD

**Issue by bbenne10** [dimitri/el-get#2266]
I'm currently getting started with emacs (from vim) and find el-get's `el-get-bundle` to be wonderful replacement for stuff like Vundle, NeoBundle and vim-plug. I'm attempting to get a simple recipe for [gruvbox](http://github.com/greduan/emacs-theme-gruvbox) working, but I can't seem to get the cloned directory added to `custom-theme-load-path` in a sane way. 
Following the advice of the zenburn colorscheme, which seems to be similarly packaged, I assumed `default-directory` would expand to the cloned repository directory (in my case `~/.emacs.d/el-get/emacs-theme-gruvbox/`), but it does not. Rather, it expands to `~/.emacs.d`. I can imagine that this is useful, but I am curious how one is to go about doing what I am doing.
Currently, my problem is "solved" by simply hardcoding the path reference from within my init-file (and not using a prepare statement at all in my ad-hoc recipe), but this feels like a hack. Should this be an additional variable exposed to the init-file, or should I simply concatenate `default-directory` and a know hard-coded string, or am I missing something else entirely? 
Furthermore, if all works as I understand it (and I've not goofed up too much), I may have discovered a bug in the Zenburn theme. It adds `default-directory` to `custom-theme-load-path`, but that directory does not contain the theme itself. This makes the theme unloadable upon startup (either via `M-x load-theme` or the init method I have described above)
For reference, my emacs.d is available [here](https://github.com/bbenne10/dotfiles/tree/master/emacs.d)

**Comment by npostavs** [comment]
Ah, it was just we forgot to change to the package directory while loading init files. Funny that nobody noticed till now. Thanks for the report.

> I may have discovered a bug in the Zenburn theme. It adds default-directory to custom-theme-load-path, but that directory does not contain the theme itself.

It works there because `default-directory` is (and always has been) changed to the package dir while loading `:prepare/:post-init/:before/:after` blocks.

**Comment by bbenne10** [comment]
Quick turn around. Thanks for the fix!
