### ISSUE TITLE
Where to report problems with recipes?

### ISSUE THREAD

**Issue by sbroberg** [dimitri/el-get#2270]
Please forgive me if this is not the right venue for this question, but where do I report problems with recipes?  I'm trying to use el-get to install malinka on a fresh install of emacs 24.5.1, OSX 10.10.5, and it's failing when trying to compile rtags.

I don't know how el-get manages its recipes, nor who maintains each recipe.  Where to begin?

**Comment by npostavs** [comment]
This is the right place to report problems with recipes.

> I don't know how el-get manages its recipes, nor who maintains each recipe.

The recipes are in this repository under `recipes/`. We don't have formal maintainers for recipes, but generally when people suggest fixes we merge them under the assumption that the users of the package know what's needed.

For rtags in particular, @LefterisJP has updated it recently (#2268).

> Where to begin?

Post the error messages from the compilation/build buffer.

**Comment by LefterisJP** [comment]
@sbroberg Please post the compilation output and I can try to help you. I am also the author of  [malinka](https://github.com/LefterisJP/malinka) and as such can help with any problems you may have.

But I believe that such issues should belong to their respective repos, so I guess you can just open an issue with the malinka github project itself so as not to clutter el-get.

**Comment by npostavs** [comment]
> But I believe that such issues should belong to their respective repos

Some el-get recipes might introduce problems by using a non-standard install procedure, or because the dependencies haven't been updated yet, so unless you see the same error by following install instructions from the package's README you shouldn't report problems upstream. For malinka, since we have the package author being involved in maintaining the el-get recipes, it's a bit of a special case...

**Comment by zhongweiy** [comment]
Hi, there, I have exactly same issue on Mac osx:
Here is a part of log:
==log begin==
CMake Error at cmake/FindLibClang.cmake:57 (message):
  Could NOT find llvm-config executable.
Call Stack (most recent call first):
  src/CMakeLists.txt:30 (find_package)


-- Configuring incomplete, errors occurred!
See also "/Users/xxx/.emacs.d/el-get/rtags/CMakeFiles/CMakeOutput.log".
==log end==

I know rtags may be built by supplying setting like: "LIBCLANG_CXXFLAGS=xxx, LIBCLANG_LIBDIR=xxx, LIBCLANG_LIBRARIES=xxx" to cmake command line (it works on my linux, but I haven't tested it on mac osx). But I would like to know if it could be solved in el-get? Or this should be solved in rtags?

**Comment by LefterisJP** [comment]
According to the [rtags readme](https://github.com/Andersbakken/rtags#c11-on-os-x) there is some special steps to build in OSX.

**Comment by sbroberg** [comment]
@zhongweiy, @LefterisJP, those instructions are a little out of date - llvm36 doesn't exist in that form anymore on homebrew.  The line I used to get llvm36 was this:

    brew install homebrew/versions/llvm36 --with-libcxx --with-clang --without-assertions --rtti --with-asan --with-lldb --with-lld --with-all-targets   

However, it seems like rtags is not building on OSX right now even with llvm36.  See my open issue here (with the rest of the commands I'm using to build rtags): https://github.com/Andersbakken/rtags/issues/481
