### ISSUE TITLE
Emacs wiki error

### ISSUE THREAD

**Issue by Pitometsu** [dimitri/el-get#2273]
```
error in process filter: could not fetch URL https://raw.github.com/emacsmirror/emacswiki.org/master/nlinum.el: error http (404)
```
But I can found *nlinum* here: https://raw.githubusercontent.com/emacsmirror/nlinum/master/nlinum.el

**Comment by npostavs** [comment]
So what needs to be fixed? `nlinum.rcp` is not an el-get recipe...

**Comment by Pitometsu** [comment]
Error occurs when I use `:type emacswiki` for package. Perhaps emacswiki type broken? Because it's available on mirror page.

**Comment by npostavs** [comment]
Looks like you should switch it to `:type emacsmirror`.

**Comment by Pitometsu** [comment]
@npostavs thanks, missed it.
