### ISSUE TITLE
File urls no longer work

### ISSUE THREAD

**Issue by dwwoelfel** [dimitri/el-get#2276]
I'm no longer able to install packages defined in file urls. It looks like https://github.com/dimitri/el-get/commit/265eb14abbd35a3e84a46fb239f6967cc4303e4c added a check for a 200 http status, which file urls don't provide.

To reproduce, add a recipe to your local filesystem, then el-get 'sync with a source that looks like:

```elisp
(list :name "Test"
      :type 'http
      :url "file:///Users/daniel/test-file.el"
      :features "test")
```

**Comment by npostavs** [comment]
> It looks like 265eb14 added a check for a 200 http status, which file urls don't provide.

Woops, so it is. Thanks for the report, should be fixed now.
