### ISSUE TITLE
support for old versions of emacs (and even packages?)

### ISSUE THREAD

**Issue by aspiers** [dimitri/el-get#2279]
It seems that if you have an older version of emacs and want a particular package, sometimes you are just out of luck.  For example `magit.rcp` has:

       :minimum-emacs-version "24.4"

When this was introduced it effectively forced all magit users to instantly upgrade.  It would be nice if older versions of recipes could be preserved somehow to avoid this.  There are four obvious possibilities:

1. Maintain branches of el-get for each emacs version
2. Allow version-specific recipes, e.g. `magit-24.3.rcp`
3. Allow including support for older versions within a single recipe
4. Declare this outside the scope of `el-get` and recommend some alternative solution for those who don't want to or can't live on the bleeding edge.

I can immediately think of disadvantages to all of them, but I'm not sure which is least bad.

Similarly (or alternately) we could think about supporting older versions of packages, e.g. `magit-1.4.2.rcp`.  I know this is probably all a big can of worms, but I think a lot of wisdom could be stolen from other places, e.g. Ruby gems and Bundler, and distro packaging.  Currently emacs package versioning and dependency tracking seems to still be somewhat in the dark ages.

**Comment by DarwinAwardWinner** [comment]
I think the most expedient solution is for users to cherry-pick whatever old recipes they want and stick them in `el-get-sources` so they override the default recipe files.

**Comment by aspiers** [comment]
That's hard enough or at least time-consuming for most users that it's more or less equivalent to option 4.  I'm not necessarily arguing against that approach, but it's essentially unsupported.

**Comment by DarwinAwardWinner** [comment]
An important consideration is that, in most cases, including your example of magit, it's not a recipe change that caused the version requirement to be added, but rather a change in the requirements causing the need to update the recipe. So there is no prior version of the magit recipe that you could revert to in order to support lower emacs versions, because every version of the magit recipe installs the current magit master. The older recipes simply don't document the version requirement. This means that "maintaining" recipes for previous emacs versions actually entails creating new recipes that obtain the packages via alternate methods (e.g. downloading tarballs of specific versions). Creating and testing all these new recipes would be a pretty large task.

**Comment by DarwinAwardWinner** [comment]
To elaborate a little more, el-get has pretty much always preferred to install packages by cloning the master branch of the vcs repo whenever possible, to get the latest version possible without waiting for a release to a package repository. (This was before MELPA greatly reduced that latency.) As such, el-get has always been more or less blind the which version of the package it is installing. It's just installing "the latest version" and that's all it really knows, unless you go out of your way to tell it more. So I'm doubtful that el-get is the right tool for the job of supporting multiple versions of packages for use on multiple emacsen.

**Comment by aspiers** [comment]
> every version of the magit recipe installs the current magit master.

Ah of course, I should have thought of that :)

> It's just installing "the latest version" and that's all it really knows, unless you go out of your way to tell it more. So I'm doubtful that el-get is the right tool for the job of supporting multiple versions of packages for use on multiple emacsen.

OK that makes sense.  Clearly users will want bleeding edge for certain packages (e.g. dependencies of packages they are personally developing) but not for others.  So if `el-get` doesn't provide complete coverage for all use cases, this seems to imply to me that it should enable or at least peacefully co-exist with other installation mechanisms which *do* support installing older versions - right?  I guess it can already support use of MELPA stable; I wonder if there is more scope for improvements though.

**Comment by DarwinAwardWinner** [comment]
Yes, you can absolutely use package.el packages for some things and el-get for others. I do that in my config: I use package.el to install everything that's available that way and el-get for everything else. The only caveat to be aware of is that if you install package X via package.el and package Y via el-get, and Y depends on X, then el-get will also want to install its own copy of package X to satisfy the dependency. You can eliminate this redundancy this by also telling el-get to install package X via package.el.

**Comment by npostavs** [comment]
You can add e.g. `:checkout "1.4.2"` to install a specific version. But potentially you also have to change other fields like `:depends` and `:build`.

**Comment by npostavs** [comment]
> Maintain branches of el-get for each emacs version

This is just a cumbersome way of maintaining version-specific recipes.

> Allow version-specific recipes, e.g. magit-24.3.rcp

If someone(tm) is willing to maintain it, we could certainly have magit-1.x.rcp, i.e. version-specific to the package, not Emacs.

> Allow including support for older versions within a single recipe

I think having multiple recipes would be easier than adding code to support multiple co-dependent properties in a single recipe.

**Comment by DarwinAwardWinner** [comment]
I could easily imagine a "variants" system within existing recipes, that would look something like this:

```elisp
(:name mypkg
       ;; Properties in the main recipe apply to all variants unless
       ;; overridden
       :website "http://mypkg-website.com"
       :type github
       :pkgname "myusername/mypkg"
       :minimum-emacs-version "24"
       :variants
       '((:variant default
                   :branch "master")
         (:variant testing
                   :branch "testing")
         (:variant legacy
                   :branch "emacs23"
                   ;; Overriding the previous version requirement for
                   ;; just this variant
                   :minimum-emacs-version "23")))
```

And then in your `el-get-sources` you would put `(:name mypkg :variant legacy)` to get the version compatible with Emacs 23. (Or el-get could even automatically select the first variant compatible with your version of Emacs.) It would be a pretty huge project to implement this, though.

**Comment by npostavs** [comment]
> It would be a pretty huge project to implement this, though.

Yeah. I would want to start with just having multiple recipes for different versions, and if we end up getting a lot of those, *maybe* consider adding something like this. My guess is magit will be pretty much the only package to end up with multiple recipes, if that.

**Comment by npostavs** [comment]
> My guess is magit will be pretty much the only package to end up with multiple recipes, if that.

Welp, looks like there is no movement on this front, so closing.

**Comment by standin000** [comment]
add this to el-get-source 
`  (:name magit :minimum-emacs-version "23"                                                                                                                            
                                 :after (magit-configuration)                                                                                                                                 
                                 :features magit                                                                                                                                              
                                 :checkout "1.4.2"                                                                                                                                            
                                 :depends (cl-lib)                                                                                                                                            
                                 :compile "magit.*\\.el\\'"                                                                                                                                   
                                 :load-path "."                                                                                                                                               
                                 :info "."                                                                                                                                                    
                                 :build `(("make" ,(format "EMACSBIN=%s" el-get-emacs) "docs"))                                                                                               
                                 :build/berkeley-unix (("gmake" ,(format "EMACSBIN=%s" el-get-emacs) "docs"))                                                                                 
                                 ;; assume windows lacks make and makeinfo                                                                                                                    
                                 :build/windows-nt (progn nil)                                                                                                                                
                                 ) `

but you still need install git-commit-mode and git-rebase-mode package first, please copy them from old repository, because they are disappeared now.
