### ISSUE TITLE
Use HTTPS whenever possible

### ISSUE THREAD

**Issue by vincentbernat** [dimitri/el-get#2287]
Hey!

As a followup to @glyph's [post](https://glyph.twistedmatrix.com/2015/11/editor-malware.html), I had a quick look at el-get. Packages on ELPA and Marmelade are forcibly using HTTP. This should be easy to fix.

After that, there is so many recipes not using HTTPS... But we can't just switch to TLS since this may not be available.

**Comment by glyph** [comment]
@vincentbernat - consider communicating with the authors of the recipes unavailable via TLS and telling them that they're going to be removed if they don't get a certificate :).
