### ISSUE TITLE
Recipe for let-alist fails with 404

### ISSUE THREAD

**Issue by akhilsbehl** [dimitri/el-get#2302]
(:name let-alist
       :description "Easily let-bind values of an assoc-list by their names."
       :builtin "25.0.50"
       :type http
       :url "http://git.savannah.gnu.org/cgit/emacs/elpa.git/plain/packages/let-alist/let-alist.el")

Contacting host: git.savannah.gnu.org:80
Error (el-get): while installing let-alist: could not fetch URL http://git.savannah.gnu.org/cgit/emacs/elpa.git/plain/packages/let-alist/let-alist.el: error http (404)

**Comment by syohex** [comment]
`let-alist` is a core package now and removed from ELPA repository.

http://git.savannah.gnu.org/cgit/emacs/elpa.git/commit/?id=2d45570ea587b8f880d3633849ff5db5a6673cael

https://elpa.gnu.org/packages/let-alist-1.0.4.el is available instead of git repository URL.

**Comment by sandao** [comment]
I have the same problem, did you resovle it?

**Comment by syohex** [comment]
How about installing from ELPA as below ? It works on Emacs 24.5.

```lisp
(el-get-bundle elpa:let-alist)
```

Or use development Emacs version. It already bundles `let-alist`.

**Comment by npostavs** [comment]
I think `let-alist` should become a `:type elpa` recipe, just like `cl-lib`.

**Comment by syohex** [comment]
@npostavs Thanks for information. I sent PR #2304.
