### ISSUE TITLE
Consider using request.el fork

### ISSUE THREAD

**Issue by abingham** [dimitri/el-get#2314]
I've recently made [a fork of request.el](https://github.com/abingham/emacs-request) which applies a couple of long-standing, important, but ignored pull-requests for the original project. It seems that the original author of request.el has abandoned it or is ignoring it. 

You should consider updating your recipe to use the new repo. [MELPA has already done so](https://github.com/milkypostman/melpa/commit/ced34c820d16ca7a58fc41c24763342357c29b8e).

**Comment by npostavs** [comment]
@tkf made some contributions to el-get a couple of years ago, but I haven't seen any activity from him in a while.

**Comment by abingham** [comment]
Yeah, he's been quiet on github for about 5 months. Strange.

**Comment by dimitri** [comment]
Let's hope for the best for @tkf, maybe he's just busy with other interesting things.

Off-topic: nice to see you're back @npostavs ;-)
And I just went on a created a gitter room for such off-topic messages, it's at https://gitter.im/dimitri/el-get and you're welcome to use it if you want to!
