### ISSUE TITLE
Add hlsl mode

### ISSUE THREAD

**Issue by vmiheer** [dimitri/el-get#2324]
Add hlsl mode to el-get.
http://sourceforge.net/projects/hlslmode/

**Comment by npostavs** [comment]
Do you use this? Seems kind of dead, last update was 2012

**Comment by vmiheer** [comment]
Two reasons for adding a package:
1. I believe there are windows users working with hlsl
2. This mode is only one available on internet (at least that's what search result says.)

**Comment by npostavs** [comment]
I invite you to submit a pull request to add the recipe, if you feel that this package is useful.

(closing, but feel free to continue to ask questions if anything is unclear)

> 1. I believe there are windows users working with hlsl

Not sure why it matters if they are windows users or not?

**Comment by vmiheer** [comment]
Because hlsl will work only on windows. And hence likely hlsl developers will work windows.
