### ISSUE TITLE
ido-yes-or-no now depends on ido-completing-read+ (part of ido-ubiquitous)

### ISSUE THREAD

**Issue by DarwinAwardWinner** [dimitri/el-get#2333]
I just released an upgrade for my ido-yes-or-no package that adds a new dependency: https://github.com/DarwinAwardWinner/ido-yes-or-no/commit/2b2149b328c358fbf13e27f81bd7adf846fb9b15

Could someone please update the recipe accordingly? (I'm not currently at a machine from which I can update/test the recipe.)

**Comment by syohex** [comment]
I suppose it is not necessary to update the recipe because `ido-yes-or-no` recipe use `elpa` type. Recipe is https://github.com/dimitri/el-get/blob/master/recipes/ido-yes-or-no.rcp.

I tested `(el-get-bundle ido-yes-or-no)` then `ido-completing-read+` is installed as dependency.

**Comment by DarwinAwardWinner** [comment]
Ok, perfect.
