### ISSUE TITLE
How to pin a recipe based on repository to a given commit?

### ISSUE THREAD

**Issue by priyadarshan** [dimitri/el-get#2334]
Hi,

I searched this repository, and read the `info` manual, but I can't find relevant information on how to pin a recipe based on repository to a given commit.

Is that possible at all?

Thanks.

**Comment by DarwinAwardWinner** [comment]
For git recipes, you can use the `:checkout` option: https://github.com/dimitri/el-get/blob/master/el-get.info#L1110

I don't know if this option has been implemented for other types of version control yet, but it shouldn't be too hard to do so.

**Comment by priyadarshan** [comment]
Thank you, I am glad `el-get` offers that. I am not sure MELPA currently offers any reliable pinning ability.

**Comment by npostavs** [comment]
> I don't know if this option has been implemented for other types of version control yet

According to the docstring of `el-get-sources`, at least for `hg` as well. Probably we shouldn't have this info in 2 places.

```
:checkout

    For `git' or `hg' recipes, a branch name, tag, or other valid
    argument to `git checkout'/`hg update'. If provided, this
    overrides any value for the `:branch' property. Unlike the
    `:branch' property, this can be any valid argument to
    `checkout', including a tag name or a commit hash.

    When given a commit hash or tag, this will lock the repo at
    that specific revision. When given a branch name, this will
    always update the repo to the latest version of that branch,
    regardless of any changes made locally (in contrast to simply
    using the `:branch' property, which will cause el-get-to try
    to merge your local changes).

    Currently this property only has meaning for `git' and `hg'
    type recipes. Other VCS-based methods may implement support
    in the future.
```

**Comment by priyadarshan** [comment]
I am glad it covers `hg` as well. That will take care of basically most of the repositories out there. It might be useful to use the word "pin" or "pinning" in the manual, as that may help finding this information more easily. Persoanlly, I would even highlight it somehow on the readme, as pinning a package to a certain version is a much needed requirement for some.

**Comment by priyadarshan** [comment]
@npostavs I knew I should have just looked at your `init.el`, I have learned so much in the past. Back then, I did not pay attention to your use of the `commit` keyword (like for example [here](https://github.com/npostavs/emacs.d/commit/142641e62a5ad803347495864eed219c26febd53)). I need to learn more!
