### ISSUE TITLE
dependency conflict (elpa & el-get) 

### ISSUE THREAD

**Issue by romankrv** [dimitri/el-get#2335]
Hi all.
I use package and el-get together. Problem is: when I add magit via el-get I have conflict with dependency in package and el-get. Both use with-editor. How to make a separately use a with-editor package? How to separate the impact from other repositories?

thanks

![screen shot 2016-02-20 at 1 27 50 am](https://cloud.githubusercontent.com/assets/42733/13192087/47e2aa64-d771-11e5-9c63-4981ca4fe1cd.png)

**Comment by npostavs** [comment]
Does it work to put `el-get` before `package-initialize`?

**Comment by romankrv** [comment]
My config has a first a package system as step of the initialization after that run el-get.

**Comment by romankrv** [comment]
you offer me to change the order of the initialization el-get as first?

**Comment by npostavs** [comment]
> you offer me to change the order of the initialization el-get as first?

Yes.

**Comment by npostavs** [comment]
Closing, as I don't see a bug here.

Call `(el-get)` before `(package-initialize)` to get el-get versions of the packages loaded, or else add `(:name dash :type elpa)` and `(:name with-editor :type elpa)` to `el-get-sources` in order to get elpa versions of the packages.
