### ISSUE TITLE
How to disable `Contacting host: raw.githubusercontent.com:443` when emacs startup?

### ISSUE THREAD

**Issue by huyu516** [dimitri/el-get#2348]
I want my emacs to be fast, so I dont want it connect to `githubusercontent` when start up,
how to do it?

my configuration:
```
(add-to-list 'load-path "~/.emacs.d/el-get/el-get.el")
(unless (require 'el-get nil 'noerror)
  (with-current-buffer
    (url-retrieve-synchronously
      "https://raw.githubusercontent.com/dimitri/el-get/master/el-get-install.el")
    (goto-char (point-max))
    (eval-print-last-sexp)))
(add-to-list 'el-get-recipe-path "~/.emacs.d/el-get-user/recipes")
(el-get 'sync)
```

**Comment by DarwinAwardWinner** [comment]
As long as el-get is installed and properly set up, it should not have to contact the network unless it actually needs to install something. However, your first line is wrong, so the code always things el-get is not installed, and tries to install it. You're supposed to add directories, not files, to the `load-path`. So the first line should be `(add-to-list 'load-path "~/.emacs.d/el-get/")`.
