### ISSUE TITLE
Troubles with custom recipes 

### ISSUE THREAD

**Issue by Crandel** [dimitri/el-get#2349]
I try to create my settings so I can just copy my .emacs.d directory to another machine, start emacs and everything installed automatically.
I have to packages without it`s recipes in el-get directory, so I try to create my own. 
When I start emacs first time, everything installed fine without errors
But when I close emacs and start again I have this error
error "El-get can not find a recipe for package "auto-virtualenv"" 

My instalation

```lisp
(require 'cl)
(require 'package)

(setq cfg:packages
  '(el-get
    auto-complete
    auto-virtualenv ;; Auto virtualenv activates virtualenv automatically when called.
    company-mode ;; Complete All
    company-jedi
    company-flx
    emmet-mode
    ergoemacs-mode
    flycheck ;; Syntax check on fly
    multiple-cursors
    py-autopep8
    py-isort
    projectile ;; Удобный менеджер проектов
    smartparens
    yasnippet
    ))

(add-to-list 'package-archives '("gnu" . "http://elpa.gnu.org/packages/") t)
(add-to-list 'package-archives '("org" . "http://orgmode.org/elpa/") t)
(add-to-list 'package-archives '("melpa" . "http://melpa.milkbox.net/packages/") t)
(package-initialize)
(add-to-list 'load-path "~/.emacs.d/el-get/el-get")

(unless (require 'el-get nil 'noerror)
    (package-refresh-contents)
    (package-install 'el-get)
    (require 'el-get))
    (el-get 'sync)

(add-to-list 'el-get-recipe-path "~/.emacs.d/el-get-user/recipes")
(el-get 'sync cfg:packages)
```

When I commit auto-virtualenv I have error with py-isort

My recipes

auto-virtualenv

```lisp
(:name auto-virtualenv
       :type github
       :pkgname "marcwebbie/auto-virtualenv"
       :description "Automatically compile Emacs Lisp libraries."
       :depends (cl-lib pyvenv s))
```

py-isort

```lisp
(:name py-isort
       :type github
       :pkgname "paetzke/py-isort.el"
       :description "Provides commands, which use the external isort tool to tidy up the imports in the current buffer")'
```

There is an error? Tell my please how to fix this

**Comment by npostavs** [comment]
Your `unless` block is not indented correctly, run `indent-region` and you get this:
```elisp
(unless (require 'el-get nil 'noerror)
  (package-refresh-contents)
  (package-install 'el-get)
  (require 'el-get))
(el-get 'sync)
```
The problem is the `(el-get 'sync)` that gets called before you've updated the recipe path. I suggest you remove it (probably it would also work to really put it inside the `unless` as in the original indentation).

**Comment by Crandel** [comment]
I found error. When I comment (el-get `sync) in this part

```lisp
(unless (require 'el-get nil t)
    (package-refresh-contents)
    (package-install 'el-get)
    (require 'el-get))
    ;(el-get 'sync)
```

everything work second time, but first time it`s not working. Somehow unless part doesn`t work correctly and run even if el-get is installed. Unfortunately I know elisp very bad and don`t know how to check if the package already installed

**Comment by Crandel** [comment]
Error with wrong closed parenthesis. I miss it
