### ISSUE TITLE
error with dependencies in jedi-core.rcp

### ISSUE THREAD

**Issue by Crandel** [dimitri/el-get#2350]
From [Melpa recipe](https://github.com/melpa/melpa/blob/master/recipes/jedi-core) we need to download few files
```lisp
files ("jedi-core.el" "jediepcserver.py" "Makefile" "setup.py"))
```
but in [your recipe](https://github.com/dimitri/el-get/blob/master/recipes/jedi-core.rcp) it\`s download only .el file
Could you fix this error? jedi:install-server doesn\`t work without this files

**Comment by npostavs** [comment]
Hmm, we don't support multiple download files (yet, see #1513) so it could be tricky.

**Comment by yuutayamada** [comment]
Although I'm not a python guy, I think you can install what you want by jedi.rcp.
seems the jdei-core.rcp is intended to download only jedi-core.el (because the recipe url only specify raw file for jedi-core.el on github)

Sorry if I was misunderstanding about your situation.

**Comment by Crandel** [comment]
@yuutayamada without these files jedi-core won`t work at all. Before using it you need to install Jedi server.

**Comment by yuutayamada** [comment]
@Crandel I mean you can install by `M-x el-get-install jedi` (not jedi-core).
It download whole repository of tkf/emacs-jedi and the repository includes: jedi-core.el, jediepcserver.py, Makefile, and setup.py.

**Comment by Crandel** [comment]
@yuutayamada I use company-mode, I don`t need jedi, only it`s core library for company-jedi. I change this recipe and will send pull request to fix this

**Comment by yuutayamada** [comment]
Oh, sorry. I understood your problem now. (probably you need to fix company-jedi.rcp to add dependencies as well)

**Comment by Crandel** [comment]
No It\`s jedi-core recipe problem, you couldn\`t install it at all, because files are missed

**Comment by yuutayamada** [comment]
company-jedi recipe doesn't include dependencies (I mean :depends), so
I thought you need to add something like `:depends (jedi-core)` in the recipe 
after you fixed jedi-core recipe.

**Comment by Crandel** [comment]
@yuutayamada I create pull request to fix this problem
