### ISSUE TITLE
Could not update package el-get

### ISSUE THREAD

**Issue by Pitometsu** [dimitri/el-get#2351]
__\*Messages\*__:
```
el-get-installation-failed: el-get: *git pull el-get* Could not update package el-get.
```
__\*git pull el-get\*__:
```
fatal: unable to access 'https://github.com/dimitri/el-get.git/': SSL certificate problem: unable to get local issuer certificate
```

**Comment by npostavs** [comment]
It seems like a problem on your end. Are you able to perform `git pull` from the command line?

**Comment by Pitometsu** [comment]
```
~/.emacs.d/el-get/el-get $ git pull
fatal: unable to access 'https://github.com/dimitri/el-get.git/': SSL certificate problem: unable to get local issuer certificate
```

**Comment by Pitometsu** [comment]
But I'm able to work (pull/push) with other github repositories via ssh here.

**Comment by npostavs** [comment]
Okay, so your system's git is unable to verify github's SSL certificates. I don't think there is anything to fix on el-get's side.

Which OS are you running?

**Comment by manandbytes** [comment]
> But I'm able to work (pull/push) with other github repositories via ssh here.

@Pitometsu (Wild guess) your HTTPS traffic is routed through proxy that terminates encrypted traffic? 

    gnutls-cli --verbose -p https github.com

will show more details.

**Comment by npostavs** [comment]
> (Wild guess) your HTTPS traffic is routed through proxy that terminates encrypted traffic?

This seems like a good guess.

> But I'm able to work (pull/push) with other github repositories via ssh here.

Probably the solution is to set `el-get-github-default-url-type` to `ssh`.  Closing, as this does not appear to be an el-get bug.

**Comment by Pitometsu** [comment]
Sorry for stupid issue. I have problem with git and ssl bug on NixOS, https://github.com/NixOS/nixpkgs/issues/3382.
