### ISSUE TITLE
Don't try to blindly install ':type apt-get' package

### ISSUE THREAD

**Issue by manandbytes** [dimitri/el-get#2357]
When on Debian, I would like to use some packages provided by the distribution, i.e.

    (el-get-bundle seq :type apt-get :pkgname "elpa-seq")

For now, el-get just blindly tries to install the package without consulting apt if the package is installed. The actual problem is in mixing:
- the check if package installed
- an actual installation of the package

under a single `sudo`ed operation that installs package if it's missing and a noop otherwise.

Allowing paswordless installation of packages to workaround this behaviour is not an option because it promotes insecure practices.

**Comment by npostavs** [comment]
Isn't `apt-get install foo` a nop if `foo` is already installed?

**Comment by manandbytes** [comment]
@npostavs I've updated description, `sudo apt-get install` waits for password.

**Comment by npostavs** [comment]
Oh yeah, that makes sense.

**Comment by manandbytes** [comment]
I think this is a bug:
- apt-get type is officially supported (at least, it's here for quite some time);
- el-get fails to proceed with installation/setup if package has been installed already.

WDYT?

**Comment by npostavs** [comment]
It fails? Is this actually a dup of #351? (though I thought `el-get-bundle` works around it).

Or maybe the "check existing install status" aspect is more like #442.

**Comment by manandbytes** [comment]
@npostavs I've updated description one more time, hope it's :ok_hand: 
https://github.com/manandbytes/.emacs.d/blob/master/.emacs.d/emacs.org#package-management

> Or maybe the "check existing install status" aspect is more like #442.

#442, comment #2382262 from @DarwinAwardWinner seems relevant:

> Maybe el-get methods should have the option of overriding the "get package status" operation by supplying an optional argument to the registration function?

**Comment by manandbytes** [comment]
Any updates?

**Comment by npostavs** [comment]
Haven't had time to look at el-get code recently, sorry. I noticed in your linked emacs.d, that you're advising `el-get-dpkg-package-status`, but it seems this function isn't even called anywhere. So yeah, this aspect really needs some improvement, patches welcome!

**Comment by npostavs** [comment]
@manandbytes Does #2391 work for you?
