### ISSUE TITLE
Misleading log message when installing ':type apt-get'

### ISSUE THREAD

**Issue by manandbytes** [dimitri/el-get#2358]
I have these two definitions:

    (el-get-bundle js2-mode :type apt-get :pkgname "elpa-js2-mode")
    (el-get-bundle skewer-mode) ;; has :depends (simple-httpd js2-mode)

When starting Emacs, Messages buffer shows that el-get tries to install `js2-mode` and not `elpa-js2-mode` with `apt-get install js2-mode`:

    Package js2-mode previously failed to install, removing it first.
    .loaddefs.el has auto save data; consider M-x recover-this-file
    el-get: updating autoloads for js2-mode
    el-get: byte-compiling autoload file
    js2-mode removed: This package has been removed successfully by el-get.
    el-get remove js2-mode
    el-get is waiting for "*apt-get install js2-mode*" to complete
    js2-mode failed to install: (error el-get: *apt-get install js2-mode* Could not install package js2-mode.)
    Package js2-mode previously failed to install, removing it first.
    el-get: updating autoloads for js2-mode
    el-get: byte-compiling autoload file
    js2-mode removed: This package has been removed successfully by el-get.
    el-get remove js2-mode
    el-get is waiting for "*apt-get install js2-mode*" to complete
    js2-mode failed to install: (error el-get: *apt-get install js2-mode* Could not install package js2-mode.)
    el-get is waiting for "*git clone skewer-mode*" to complete
    el-get: Package skewer-mode installed.
    el-get is waiting for "*git submodule update*" to complete
    el-get: git submodule update ok
    el-get is waiting for "byte-compile" to complete
    el-get: el-get-build skewer-mode: byte-compile ok.
    el-get: updating autoloads for skewer-mode

From the logs two things sould be obvoious:
- what `el-get` package el-get is trying to install
- what `apt-get` command is executed

**Comment by npostavs** [comment]
Just looking at the source, I *think* this just a problem of messaging, and the actual `apt-get` command is using `:pkgname`, see [el-get-apt-get-install][1]:

```elisp
(defun el-get-apt-get-install (package url post-install-fun)
  "echo $pass | sudo -S apt-get install PACKAGE"
  (let* ((source  (el-get-package-def package))
         (pkgname (or (plist-get source :pkgname) (el-get-as-string package)))
         (name (format "*apt-get install %s*" package))
         ...)

    (el-get-start-process-list
     ...
                      :command-name ,name
                      :program ,(el-get-executable-find "sudo")
                      :args ("-S" ,el-get-apt-get "install" ,pkgname)
     ...
```

[1]: https://github.com/dimitri/el-get/blob/45b5d9a338c4da6b7fd1b20f06b88eb30026aeb6/methods/el-get-apt-get.el#L125-L142
