### ISSUE TITLE
Compatibiilty with recentf: Don't add .loaddefs.el

### ISSUE THREAD

**Issue by xuhdev** [dimitri/el-get#2363]
After enable recentf-mode, it seems that `.laddefs.el` is frequently added to the list, while I didn't open it in Emacs myself. Is it possible to not add the file into the recent file list, when el-get does something on it? Of course when I manually edit it, I still prefer it is added to the list.

**Comment by npostavs** [comment]
Does #2364 work?

**Comment by xuhdev** [comment]
It works except the following case. When I call `el-get-remove` and exit Emacs after that, a prompt would pop up and ask me whether I want to save `.loaddeffs.el`. In this case, the `.loaddefs.el` is still added to recentf.

**Comment by npostavs** [comment]
> When I call el-get-remove and exit Emacs after that, a prompt would pop up and ask me whether I want to save .loaddeffs.el

Hmm, that's a bug in itself. El-get should be saving it automatically (I've noticed this problem before, but I hadn't made the connection to `el-get-remove`). I added another commit that should fix this, could you try again? Thanks for testing.

**Comment by xuhdev** [comment]
Yes, it works now! Thanks!
