### ISSUE TITLE
Revert fe2533e234cab4c04488382b9176ac569b0e8d2a since pdf-tools reverts back its bundling with tablist

### ISSUE THREAD

**Issue by xuhdev** [dimitri/el-get#2367]
#2112 came when tablist was bundled with pdf-tools. However, pdf-tools removed tablist again a few days ago.... politza/pdf-tools@0277eec38107c4d9a5263d7817e297ff0cf0d3dc

**Comment by npostavs** [comment]
Can you test #2368 please?
