### ISSUE TITLE
no match install

### ISSUE THREAD

**Issue by Dauth** [dimitri/el-get#2381]
i am trying to install ropemacs using el-get with the below command. However i keep getting no match, may i know what is the issue?

M-x el-get-install ropemacs

**Comment by npostavs** [comment]
Does `M-x el-get-describe ropemacs` work?

**Comment by Dauth** [comment]
think i got it to worked already. thanks alot

**Comment by Dauth** [comment]
seems like now there is an issue 

For information about GNU Emacs and the GNU system, type C-h C-a.
Making completion list...
el-get install rope
el-get: Package rope installed.
el-get: git submodule update ok
el-get: el-get-build rope: byte-compile ok.
el-get: updating autoloads for rope
Saving file c:/Users/Owner/AppData/Roaming/.emacs.d/el-get/.loaddefs.el...
Wrote c:/Users/Owner/AppData/Roaming/.emacs.d/el-get/.loaddefs.el
el-get: byte-compiling autoload file
Compiling c:/Users/Owner/AppData/Roaming/.emacs.d/el-get/.loaddefs.el...done
Wrote c:/Users/Owner/AppData/Roaming/.emacs.d/el-get/.loaddefs.elc
el-get install ropemode
rope installed: This package has been installed successfully by el-get.
el-get: Package ropemode installed.
el-get: git submodule update ok
el-get: el-get-build ropemode: byte-compile ok.
el-get: updating autoloads for ropemode
Saving file c:/Users/Owner/AppData/Roaming/.emacs.d/el-get/.loaddefs.el...
Wrote c:/Users/Owner/AppData/Roaming/.emacs.d/el-get/.loaddefs.el
el-get: byte-compiling autoload file
Compiling c:/Users/Owner/AppData/Roaming/.emacs.d/el-get/.loaddefs.el...done
Wrote c:/Users/Owner/AppData/Roaming/.emacs.d/el-get/.loaddefs.elc
el-get install pymacs
ropemode installed: This package has been installed successfully by el-get.
el-get: Package pymacs installed.
el-get: git submodule update ok
pymacs failed to install: (error el-get: make el-get could not build pymacs [make])
error in process sentinel: el-get-installation-failed: el-get: make el-get could not build pymacs [make]
error in process sentinel: el-get: make el-get could not build pymacs [make]

**Comment by npostavs** [comment]
Post contents of `*el-get-build: pymacs*`

**Comment by Dauth** [comment]
sorry, beginner in emacs here, do i type it in M-x ?

**Comment by npostavs** [comment]
Sorry, I meant contents of the buffer named `*el-get-build: pymacs*`

**Comment by Dauth** [comment]
I think this is from the buffer?
'make' is not recognized as an internal or external command,
operable program or batch file.

**Comment by npostavs** [comment]
Oh, you're on Windows. According to the pymacs manual it should be possible to install without `make` installed. Try editing the `pymacs.rcp` file to add a `:build/windows-nt` section like this:
```elisp
(:name pymacs
       :description "Interface between Emacs Lisp and Python"
       :type github
       :pkgname "pinard/Pymacs"
       :prepare
       (progn
         ;; do PYTHONPATH=~/.emacs.d/el-get/pymacs/:$PYTHONPATH
         (el-get-envpath-prepend "PYTHONPATH" default-directory)
         (autoload 'pymacs-load "pymacs" nil t)
         (autoload 'pymacs-eval "pymacs" nil t)
         (autoload 'pymacs-exec "pymacs" nil t)
         (autoload 'pymacs-call "pymacs")
         (autoload 'pymacs-apply "pymacs"))
       :build (("make"))
       ;; Assume windows lacks make, emulate what make does, as
       ;; suggested in manual (although we're emulating "make", not
       ;; "make install").
       :build/windows-nt
       (("python" "pppp" "-C" "ppppconfig.py"
         "Pymacs.py.in" "pppp.rst.in" "pymacs.el.in" "pymacs.rst.in" "contrib" "tests")
        ("python" "setup.py" "--quiet" "build")))
```

**Comment by npostavs** [comment]
Although pinard/Pymacs#60 suggests there might be trouble...
