### ISSUE TITLE
el-get-sources not defined when install el-get

### ISSUE THREAD

**Issue by zhengjiezxxy** [dimitri/el-get#2390]
I try to install emacs by the following method:

```
;; So the idea is that you copy/paste this code into your *scratch* buffer,
;; hit C-j, and you have a working el-get.
(url-retrieve
 "https://raw.githubusercontent.com/dimitri/el-get/master/el-get-install.el"
 (lambda (s)
   (goto-char (point-max))
   (eval-print-last-sexp)))

```

But it display error like following:
Symbol's value as variable is void: el-get-sources

And turns out this line in el-get-install.el has thrown an exception.
  (unless (require 'el-get nil t)

After delete this line, I can install el-get successfully.

I met this error both on Linux and Windows. Emacs version is 24.5 and 25.0.

**Comment by npostavs** [comment]
Not seeing it here (`GNU Emacs 25.0.93.3 (x86_64-unknown-linux-gnu, X toolkit) of 2016-05-05`). Can you get a backtrace if you set `debug-on-error` to `t`?

**Comment by zhengjiezxxy** [comment]
After I remove el-get by
" mv .emacs.d/el-get ..".
And restart emacs, it display the error again.
"
Warning (initialization): An error occurred while loading `/home/zhengjie4/.emacs.d/init.el':

Symbol's value as variable is void: el-get-sources

To ensure normal operation, you should investigate and remove the
cause of the error in your initialization file.  Start Emacs with
the `--debug-init' option to view a complete error backtrace.
"

And el-get init-code in init.el is:
"
;;; el-get
(add-to-list 'load-path "~/.emacs.d/el-get/el-get")

(unless (require 'el-get nil 'noerror)
  (with-current-buffer
      (url-retrieve-synchronously
       "https://raw.githubusercontent.com/dimitri/el-get/master/el-get-install.el")
    (goto-char (point-max))
    (eval-print-last-sexp)))

(add-to-list 'el-get-recipe-path "~/.emacs.d/el-get-user/recipes")
(el-get 'sync)
"

So the error is reproduciable here.

**Comment by zhengjiezxxy** [comment]
Turns out it's caused by module name contamination. I have installed another package "scratch" by package-install, https://github.com/ieure/scratch-el/blob/master/el-get.el. 
And there there is a file named el-get.el.  But I still don't know how the error message comes out(I guess maybe el-get.el in scratch-el package cannot be loaded).

**Comment by zhengjiezxxy** [comment]
And there is the backtrace:

Debugger entered--Lisp error: (void-variable el-get-sources)
  byte-code("\301\302\"\303\304!\207" [el-get-sources append (:name scratch :type git :url "git@github.com:cbbrowne/scratch-el.git" :load-path "." :info "." :build ("make")) require scratch] 3)
  #<subr require>(el-get nil t)
  ad-Advice-require(#<subr require> el-get nil t)
  apply(ad-Advice-require #<subr require> (el-get nil t))
  require(el-get nil t)
  (if (require (quote el-get) nil t) nil (if (file-directory-p el-get-root) nil (make-directory el-get-root t)) (let* ((package "el-get") (buf (switch-to-buffer "*el-get bootstrap*")) (pdir (file-name-as-directory (concat el-get-root package))) (git (or (executable-find "git") (error "Unable to find `git'"))) (url (or (and (boundp (quote el-get-git-install-url)) el-get-git-install-url) "https://github.com/dimitri/el-get.git")) (default-directory el-get-root) (process-connection-type nil) (status (call-process git nil (cons buf (quote (t))) t "--no-pager" "clone" "-v" url package))) (if (zerop status) nil (error "Couldn't clone el-get from the Git repository: %s" url)) (let* ((branch (cond ((and ... el-get-install-branch)) ((boundp ...) "master") ((plist-get ... :branch)) ("master"))) (remote-branch (format "origin/%s" branch)) (default-directory pdir) (bstatus (if (string-equal branch "master") 0 (call-process git nil (list buf t) t "checkout" "-t" remote-branch)))) (if (zerop bstatus) nil (error "Couldn't `git checkout -t %s`" branch))) (add-to-list (quote load-path) pdir) (add-to-list (quote load-path) el-get-root) (load package) (let ((el-get-default-process-sync t) (el-get-verbose t)) (el-get-post-install "el-get")) (if (boundp (quote el-get-install-skip-emacswiki-recipes)) nil (condition-case err (el-get-emacswiki-build-local-recipes) (error (display-warning (quote el-get) (error-message-string err))))) (save-current-buffer (set-buffer buf) (goto-char (point-max)) (insert "\nCongrats, el-get is installed and ready to serve!"))))
  (let ((el-get-root (file-name-as-directory (or (and (boundp (quote el-get-dir)) el-get-dir) (concat (file-name-as-directory user-emacs-directory) "el-get"))))) (if (and (fboundp (quote gnutls-available-p)) (gnutls-available-p)) nil (display-warning (quote (el-get tls)) (concat "Your Emacs doesn't support HTTPS (TLS)" (if (eq system-type (quote windows-nt)) ",\n  see https://github.com/dimitri/el-get/wiki/Installation-on-Windows." ".")))) (if (file-directory-p el-get-root) (progn (add-to-list (quote load-path) el-get-root))) (if (require (quote el-get) nil t) nil (if (file-directory-p el-get-root) nil (make-directory el-get-root t)) (let* ((package "el-get") (buf (switch-to-buffer "*el-get bootstrap*")) (pdir (file-name-as-directory (concat el-get-root package))) (git (or (executable-find "git") (error "Unable to find `git'"))) (url (or (and (boundp ...) el-get-git-install-url) "https://github.com/dimitri/el-get.git")) (default-directory el-get-root) (process-connection-type nil) (status (call-process git nil (cons buf (quote ...)) t "--no-pager" "clone" "-v" url package))) (if (zerop status) nil (error "Couldn't clone el-get from the Git repository: %s" url)) (let* ((branch (cond (...) (... "master") (...) ("master"))) (remote-branch (format "origin/%s" branch)) (default-directory pdir) (bstatus (if (string-equal branch "master") 0 (call-process git nil ... t "checkout" "-t" remote-branch)))) (if (zerop bstatus) nil (error "Couldn't `git checkout -t %s`" branch))) (add-to-list (quote load-path) pdir) (add-to-list (quote load-path) el-get-root) (load package) (let ((el-get-default-process-sync t) (el-get-verbose t)) (el-get-post-install "el-get")) (if (boundp (quote el-get-install-skip-emacswiki-recipes)) nil (condition-case err (el-get-emacswiki-build-local-recipes) (error (display-warning (quote el-get) (error-message-string err))))) (save-current-buffer (set-buffer buf) (goto-char (point-max)) (insert "\nCongrats, el-get is installed and ready to serve!")))))
  eval-buffer()  ; Reading at buffer position 3394
  #<subr call-interactively>(eval-buffer record nil)
  ad-Advice-call-interactively(#<subr call-interactively> eval-buffer record nil)
  apply(ad-Advice-call-interactively #<subr call-interactively> (eval-buffer record nil))
  call-interactively(eval-buffer record nil)
  command-execute(eval-buffer record)
  execute-extended-command(nil "eval-buffer")
  smex-read-and-run(("toggle-debug-on-error" "describe-package" "eval-buffer" "edebug-defun" "compile" "eshell" "visit-tags-table" "package-install" "gud-gdb" "w3m-goto-url" "semantic-ia-fast-jump" "dark" "list-processes" "imenu" "magit-log" "load-theme" "magit-blame" "load-library" "vc-print-log" "eval-print-last-sexp" "toggle-frame-fullscreen" "w3m" "vc-diff" "run-python" "python-mode" "ctags-update" "git-blame-mode" "semantic-symref" "package-list-packages" "ctags-auto-update-mode" "ag" "cd" "ri" "5x5" "arp" "dbx" "dig" "erc" "ert" "eww" "ftp" "gdb" "irc" "jdb" "man" "mpc" "pdb" "pwd" "rsh" "sdb" ...))
  smex()
  #<subr call-interactively>(smex nil nil)
  ad-Advice-call-interactively(#<subr call-interactively> smex nil nil)
  apply(ad-Advice-call-interactively #<subr call-interactively> (smex nil nil))
  call-interactively(smex nil nil)
  command-execute(smex)

**Comment by zhengjiezxxy** [comment]
And when evaluate the following lisp:
(setq a (append 2 a))
the error message is:
setq: Symbol's value as variable is void: a
seems the errror is caused by this. 
Thanks.

**Comment by npostavs** [comment]
Ah, it's exactly this upstream issue: ieure/scratch-el#4. So it looks like scratch-el isn't being maintained, therefore I recommend you either fix it yourself, or stop using it. Or I guess you could ask the melpa guys to drop that file from their recipe.
