### ISSUE TITLE
error "Failed to find end of headers in HTTP response"

### ISSUE THREAD

**Issue by seudut** [dimitri/el-get#2398]
I use el-get to fetch some package on emacs wiki, here is my elisp code snippet

    (el-get-bundle color-occur
      :url "http://www.emacswiki.org/emacs/download/color-occur.el"
      (require 'color-occur))

But after eval this, I get the error

    Error (el-get): while installing color-occur: Failed to find end of headers in HTTP response from http://www.emacswiki.org/emacs/download/color-occur.el for package color-occur; see buffer  *http www.emacswiki.org:443*-974444

Does `el-get` support to fetch package by this way?

**Comment by npostavs** [comment]
Works for me. What's your Emacs and OS versions?

Does evaluating `(switch-to-buffer (url-retrieve-synchronously "http://www.emacswiki.org/emacs/download/color-occur.el"))` show something interesting?

**Comment by seudut** [comment]
Thanks, 

after evaluating `(switch-to-buffer (url-retrieve-synchronously "http://www.emacswiki.org/emacs/download/color-occur.el"))`, it just switch to the buffer `buffer  *http www.emacswiki.org:443*-627347`, but nothing output. and the message is just `Contacting host: www.emacswiki.org:80`

My OS is Mac OSX 10.10 and Emacs version is

    "GNU Emacs 25.1.50.2 (x86_64-apple-darwin14.5.0, NS appkit-1348.17 Version 10.10.5 (Build 14F27)) of 2016-06-02"

installed by `brew`

**Comment by npostavs** [comment]
Okay, sounds like [Emacs bug #23225](http://debbugs.gnu.org/cgi/bugreport.cgi?bug=23225). I'm closing this el-get issue, since there's not really anything el-get can do to fix it.
