### ISSUE TITLE
google code refrences still in recipie database.

### ISSUE THREAD

**Issue by timoc** [dimitri/el-get#2412]
Hi,

I tried to install org-outlook (which depends on soap-client) and it failed. After some digging i came to the conclusion that the recipe was wrong because it pointed at the now defunct code.google.com. A quick grep of the recipe folder picks up other recipes. 
in the last days of google code, they offered a mechanism to 'transfer to github' so it is likley now where these packages are maintained.

`tim@zangbandv2[2]:~ $ grep -r code.google.com .dotfiles/zemacsen/el-get/el-get/recipes/`
- [X] ~~soap-client.rcp:       :website "http://code.google.com/p/emacs-soap-client/"~~
- [X] ~~soap-client.rcp:       :url "https://code.google.com/p/emacs-soap-client/")~~
- [ ] confluence-el.rcp:       :website "http://code.google.com/p/confluence-el"
- [X] ~~go-def.rcp:       :pkgname "code.google.com/p/rog-go/exp/cmd/godef"~~
- [X] ~~emacswiki/struct+.rcp::description "has moved to http://code.google.com/p/emacs-ontology-project/source"~~
- [X] ~~csharp-mode.rcp:       :website "https://code.google.com/p/csharpmode/"~~
- [ ] project-mode.rcp:       :website "http://code.google.com/p/emacs-project-mode/"
- [X] ~~geben.rcp:       :website "https://code.google.com/p/geben-on-emacs/"~~
- [ ] vc-clearcase.rcp:       :url "https://code.google.com/p/vc-clearcase/"
- [ ] xahk-mode.rcp: :url http://ergoemacs.googlecode.com/svn/trunk/packages/xahk-mode.el2 (#2634)

**Comment by AndersonTorres** [comment]
Sites I have found. I will try to update the recipes and fix some issues (creating the github projects).

[ ] confluence-el: https://sourceforge.net/projects/confluence-el/
[ ] vc-clearcase https://github.com/alex-hhh/vc-clearcase
[ ] xahk-mode.el: https://github.com/xahlee/xahk-mode.el



[ ] emacs-project-mode https://code.google.com/archive/p/emacs-project-mode/source/default/source
