### ISSUE TITLE
ensime

### ISSUE THREAD

**Issue by rexshihaoren** [dimitri/el-get#2435]
I am trying to install ensime with el-get on mac. It installed successfully, but when I entered a project and use M-x ensime, it gives me "Cannot open load file: no such file or directory, scala-mode-syntax"

**Comment by npostavs** [comment]
Sounds like there is a depedency missing, can you try running `M-x el-get-auto-update-dependencies RET ensime RET` and see if that updates `ensime.rcp` correctly?

**Comment by npostavs** [comment]
> Sounds like there is a depedency missing

Actually, looking at this more closely, it's probably that you still have the old `scala-mode` installed. Try `M-x el-get-reinstall RET scala-mode RET`.
