### ISSUE TITLE
Why can't I use el-get-install to install color-theme?

### ISSUE THREAD

**Issue by moyotar** [dimitri/el-get#2447]

**Comment by syohex** [comment]
Do you install [tar](https://www.gnu.org/software/tar/)(Windows version is [here](http://gnuwin32.sourceforge.net/packages/gtar.htm)) in your platform ?

**Comment by moyotar** [comment]
## Yes, I had made it after finishinig installing tar. Thanks!

**Comment by syohex** [comment]
Could you close this issue ?
