### ISSUE TITLE
Can't install ELPA packages without a "secure" :url

### ISSUE THREAD

**Issue by dsedivec** [dimitri/el-get#2467]
Steps to reproduce:

1. `emacs -Q`
2. Put this in `*scratch*`:
    
    ```elisp
    (setq user-emacs-directory "/tmp/egb/emacs")
    (url-retrieve
     "https://raw.githubusercontent.com/dimitri/el-get/master/el-get-install.el"
     (lambda (s)
       (goto-char (point-max))
       (eval-print-last-sexp)))
    (el-get-install "queue")
    ```
3. `M-x eval-buffer`

Expected result: `queue` is installed from ELPA.

Observed result: Installation fails with the message "apply: URL is nil, can’t decide if it’s safe to install package ’queue’".

Tested against GNU Emacs 25.1.1 (from https://emacsformacosx.com/) on OS X 10.11.6.

Additional comments: I believe this will happen for any ELPA recipe which does not have a `:url` that starts with `https` because of the `(el-get-insecure-check package url)` call at the top of `el-get-elpa-install`.  As far as I know, ELPA recipes ignore `:url` anyway, so I suspect this check is incorrect.  If we want to check if an ELPA recipe is "secure" then maybe we need to find out what URL `package-install` will use for ELPA?

To reiterate, this problem does affect other packages.  In addition to `queue` I've also encountered this with `adaptive-wrap` and `csv-mode`.

**Comment by npostavs** [comment]
Yeah, I noticed that earlier. Haven't had time to do anything about it.

https://github.com/dimitri/el-get/pull/2461#issuecomment-247874899

**Comment by f0086** [comment]
This bug is specially anoying because the popular `cider` package depends on the `queue` package. So no proper clojure development in Emacs possible :(

**Comment by dsedivec** [comment]
> This bug is specially anoying because the popular cider package depends on the queue package. So no proper clojure development in Emacs possible :(

@f0086 as a temporary workaround I believe you can use:

```elisp
(add-to-list 'el-get-sources '(:name queue :url "https://elpa.gnu.org/packages/queue.html"))
```

Then you should be able to install queue.  You can follow this same pattern for any packages similarly affected.

**Comment by npostavs** [comment]
Also, if you use Emacs 24.5 or greater, the patch in #2468 should work fine.

**Comment by npostavs** [comment]
As of facea41fde82a4e90a5e20d90fe54e4fc02c5fec, this will only fail if you set `el-get-allow-insecure` to `nil`.

**Comment by npostavs** [comment]
I believe #2477 fixes this.

**Comment by zilti** [comment]
For what I noticed, yes, this fixes the problem.
