### ISSUE TITLE
autoloads scan error installing lui

### ISSUE THREAD

**Issue by ironchicken** [dimitri/el-get#2494]
I'm trying to install [emacs-slack](https://github.com/yuya373/emacs-slack) which seems to depend on `lui`. I've added a `el-get-sources` entry for `emacs-slack`:

    (:name emacs-slack
        :description "Slack client for Emacs"
        :type github
        :pkgname "yuya373/emacs-slack")

 But I can't install `lui`. I get the following:

    el-get install lui
    Wrote /home/me/.emacs.d/el-get/lui/lui.el
    el-get: el-get-build lui: byte-compile ok.
    el-get: updating autoloads for lui
    Generating autoloads for lui/lui.el...
    lui failed to install: (scan-error Unbalanced parentheses 7215 7862)
    el-get-installation-failed: Scan error: "Unbalanced parentheses", 7215, 7862

There are some suggestions that this could be related to `coding-system-for-read` but mine is set to `nil`.

**Comment by npostavs** [comment]
Where's the recipe for lui?

**Comment by ironchicken** [comment]
Um, good question. It's an auto-complete option on `el-get-install` but I'm not sure why. It seems it's available via `package-install`.

I've just done a bit more research and it seems that `lui` is now part of `circe` (another IRC client). `circe` installs correctly from `el-get` and so now I can successfully `(require 'lui)`.

So I guess this issue can be closed because it now works-for-me.
