### ISSUE TITLE
If a package that el-get don't konw its recipe.

### ISSUE THREAD

**Issue by moyotar** [dimitri/el-get#2500]
Hi, @dimitri.
There's a package I want from `MELPA`. But I can't install it by `el-get` because `el-get` can't find it. Unless to make a local recipe for it to let `el-get` know, is there a way to set `MELPA` as a source in which `el-get` find packages automatically?

**Comment by syohex** [comment]
`el-get-bundle` supports installing from elpa(melpa) as below.

```
(el-get-bundle elpa:some-package)
```

**Comment by npostavs** [comment]
Or running `el-get-elpa-build-local-recipes` will build recipes based on your current package.el repositories.

**Comment by moyotar** [comment]
@syohex @npostavs Thanks!
