### ISSUE TITLE
elpy recipe not working

### ISSUE THREAD

**Issue by renatocan** [dimitri/el-get#2506]
Hi,

I am having an issue when trying to install elpy using el-get. When I try to install it, I get the error message "elpy-django.el:27:1:Error: Cannot open load file: No such file or directory, s".

It seems that it is a known problem that has been solved (see issue https://github.com/jorgenschaefer/elpy/issues/1038#issuecomment-269139906).

I've contacted the mantainer of elpy but the issue seems to be with the el-get recipe since when I try to install elpy manually, following the provided instructions, the installation is successful.

I don't know much about el-get recipes. Can someone point me out where to start to solve this issue?

Thanks,

Renato.

**Comment by npostavs** [comment]
el-get's recipes rely on manually specifying dependencies, so they need to be updated when upstream changes. In this case, to match what's listed in https://github.com/jorgenschaefer/elpy/blob/master/elpy-pkg.el

Should be fixed now.
