### ISSUE TITLE
Error when 2nd run

### ISSUE THREAD

**Issue by conao** [dimitri/el-get#2532]
I use el-get with init-loader.
1st run (installation) is correct, but error occurred at 2nd run.

init-loader-show-log: 1st run
![capture 2017-05-13 13 47 04](https://cloud.githubusercontent.com/assets/4703128/26022532/08197678-37e3-11e7-9233-bb3923366779.png)

initloader-show-log: 2nd run
![capture 2017-05-13 13 47 47](https://cloud.githubusercontent.com/assets/4703128/26022538/1423e598-37e3-11e7-9639-16f104a40525.png)

May be error occurred at 90_el-get.el:line39
``` elisp
(el-get-bundle! conao/auto-save-buffers
  (run-with-idle-timer 0.5 t 'auto-save-buffers))
```

I prepare test case at https://github.com/conao/.emacs-test
This .emacs also error occurred (above screen shot is this test case)

Run like that
``` shell
cd
git clone https://github.com/conao/.emacs-test
emacs -q -l ~/.emacs-test/init.el
```
--emacs quit--

``` shell
emacs -q -l ~/.emacs-test/init.el
```

**Comment by npostavs** [comment]
I think this is a dup of #2232.

**Comment by conao** [comment]
Thank you for your comment and I overlook that conversation.
But there are too much point to approach this problem 
so I didn't understand 'actualy' what to do.

What is the simple approach this problem?
Not to call `(el-get 'sync)` ?

**Comment by npostavs** [comment]
> But there are too much point to approach this problem

Yeah, I've added a summary in the OP.

> What is the simple approach this problem?
> Not to call `(el-get 'sync)` ?

You can call it only after the `el-get-bundle` calls.

**Comment by conao** [comment]
Good! I got it!
Thank you for your support!

``` elisp
(unless (require 'el-get nil 'noerror)
  (with-current-buffer
      (url-retrieve-synchronously
       "https://raw.github.com/dimitri/el-get/master/el-get-install.el")
    (goto-char (point-max))
    (eval-print-last-sexp)))

(el-get-bundle conao/auto-save-buffers)
(el-get-bundle conao/other-window-or-split)
(el-get 'sync)
```
