### ISSUE TITLE
proof-general fails to install

### ISSUE THREAD

**Issue by elliottslaughter** [dimitri/el-get#2543]
When I attempt to use el-get to install proof-general (PG), I see the following:

```
Error (el-get): while installing proof-general: Cannot open load file: no such file or directory, /home/.../generic/proof-site
```

Where `/home/...` is the path I happened to be in when running the installation. If I subsequently reload then it complains about trying to load it at the path `~/.emacs.d/el-get/generic/proof-site`. The path where the file is actually located is `~/.emacs.d/el-get/proof-general/generic/proof-site`.

As best I can tell, this seems to be a bizarre interaction between the [`pg-init.el` file](https://github.com/ProofGeneral/PG/blob/master/pg-init.el) and el-get. The file attempts to locate PG by its own path. For some reason I cannot entirely fathom, el-get takes the contents of `pg-init.el` and dumps them into `~/.emacs.d/el-get/.loaddefs.el`. Surprise, this is in a different directory and now the file doesn't load properly.

This behavior is almost entirely opaque to me so I'm not sure whether I should be reporting it here or to PG. If the problem is upstream please say so (ideally along with a concrete hint I can take to them so they know what to do to fix it).

Thanks.

**Comment by npostavs** [comment]
> The file attempts to locate PG by its own path. For some reason I cannot entirely fathom, el-get takes the contents of pg-init.el and dumps them into ~/.emacs.d/el-get/.loaddefs.el

It's because `pg-init.el` has `;;;###autoload` cookies. However, el-get puts these autoloaded statements into a different directory which is different from what package.el does, and in this case, doesn't work.

Should be fixed by #2544.
