### ISSUE TITLE
base16 package currently broken

### ISSUE THREAD

**Issue by belak** [dimitri/el-get#2545]
The base16-theme was updated in melpa a while back to work with an updated folder structure, but I was unaware that el-get used different package definitions. I'd be happy to make the changes, but it might be a while because I've never used el-get before.

https://github.com/melpa/melpa/blob/master/recipes/base16-theme

Edit: for clarification, the build/*.el files are all the theme files, and need to be included in the main dir of the final package.

**Comment by npostavs** [comment]
> the build/*.el files are all the theme files, and need to be included in the main dir of the final package.

el-get doesn't have a "final package", so its recipe should follow the approach for "development" I guess https://github.com/belak/base16-emacs#development

**Comment by belak** [comment]
In all honesty, not copying the files and just adding the build directory to the theme load path is slightly better than what I had to do for melpa (if that's possible) because the current name of the package in melpa (base16-theme) causes the main file to show up when you call load-theme, even when it's not a valid theme at all.

**Comment by belak** [comment]
Thanks!
