### ISSUE TITLE
Where to add package-specific settings

### ISSUE THREAD

**Issue by lobachevzky** [dimitri/el-get#2546]
In your README, you write

> The easiest way to setup a given package is to add its initialization code to a file named init-<package>.el with <package> replaced with the package name. This file needs to be placed in the directory el-get-user-package-directory (defaults to nil, you have to set a value for it, like for example ~/.emacs.d/el-get-init-files/).

I added
```
(setq 'el-get-user-package-directory "~/.emacs.d/el-get-init-files/")
```
to the bottom of `~/.emacs` and then added `init-evil.el` to this directory, which contains the following line:
```
(evil-mode 1)
```

However, on start up, evil-mode is not on, and I have to type `M-x evil-mode`. What am I missing? Thanks.

**Comment by npostavs** [comment]
> I added
> 
>     (setq 'el-get-user-package-directory "~/.emacs.d/el-get-init-files/")
> 
> to the bottom of ~/.emacs

I think there are two problems here:
1. You have a leading `'` before the variable name. 
2. The setting shouldn't go at the bottom, it should go before you call `el-get`.

**Comment by lobachevzky** [comment]
Perfect that worked! One question though:
> The setting shouldn't go at the bottom, it should go before you call el-get.
I'm still very new to `emacs`. Should this be at the very top of the init file before `(package-initialize)` or at the bottom right before `(el-get 'sync)`? Thanks.

**Comment by npostavs** [comment]
> Should this be at the very top of the init file before `(package-initialize)` or at the bottom right before `(el-get 'sync)`? Thanks.

Anywhere before `(el-get 'sync)` should be fine.

**Comment by lobachevzky** [comment]
Thanks.
