### ISSUE TITLE
How to make recipe for elpa package

### ISSUE THREAD

**Issue by lobachevzky** [dimitri/el-get#2548]
Hi,
I have read through your documentation and also looked at a few of the existing recipes for inspiration. I am trying to install the package [intero](http://commercialhaskell.github.io/intero/) but I am also generally trying to learn how to put together an el-get recipe when a package only gives instructions for installation through MELPA. According to the website, the only steps for MELPA installation are:

```
(package-install 'intero)
(add-hook 'haskell-mode-hook 'intero-mode)
```

So just to start I tried:
```
intero.rcp
---------------------------------
(:name intero
       :description "Complete interactive development program for Haskell"
       :type elpa)
```

When I ran `M-x el-get-install` I got the error 'Wrong type argument: arrayp, nil'. This sounds like a basic syntax error, but I couldn't find much online that related to my situation.

Thinking that perhaps installation direct from GitHub would be easier, I tried:

```
intero.rcp
---------------------------------
(:name intero
       :description "Complete interactive development program for Haskell"
       :type github
       :pkgname "commercialhaskell/intero")
```

This time, the installation runs without errors, but `M-x intero-mode` does not show up as an option, and as far as I can tell, emacs has no visibility on the package. 

Anyway, I really hope to use el-get as my primary method of package management, since it seems much more principled and portable than the alternatives. Thanks for your work on this project, and thanks for your help.

**Comment by lobachevzky** [comment]
Ok. Just figured it out. This was what needed to go into `intero.rcp`:
```
(:name intero
       :description "Complete interactive development program for Haskell"
       :type elpa
       :repo ("marmalade" . "http://melpa.org/packages/"))
```
If you have any insight into the 'arrayp, nil' error, I would appreciate it though.

**Comment by npostavs** [comment]
> When I ran `M-x el-get-install` I got the error 'Wrong type argument: arrayp, nil'. This sounds like a basic syntax error, but I couldn't find much online that related to my situation.

Not sure what this is from, if you `M-x toggle-debug-on-error` can you get a backtrace?

> Thinking that perhaps installation direct from GitHub would be easier, I tried:
> [...]
> This time, the installation runs without errors, but M-x intero-mode does not show up as an option, and as far as I can tell, emacs has no visibility on the package.

You might need to add `:load-path "elisp/"` since it seems that's where the elisp source code is.

**Comment by npostavs** [comment]
> > When I ran `M-x el-get-install` I got the error 'Wrong type argument: arrayp, nil'. This sounds like a basic syntax error, but I couldn't find much online that related to my situation.
> 
> Not sure what this is from, if you `M-x toggle-debug-on-error` can you get a backtrace?
> 

Could be the same as https://github.com/dimitri/el-get/pull/2521#issuecomment-291094892 actually, which might mean you need to do `(package-refresh-contents)`.

**Comment by lobachevzky** [comment]
Hmm... I probably need to learn more list to get to the bottom of this.

**Comment by Pitometsu** [comment]
@lobachevzky 
```elisp
(:name intero
               :type svn
               :url "https://github.com/commercialhaskell/intero/trunk/elisp"
               :description "Complete interactive development program for Haskell"
               :depends (flycheck company-mode))
```

**Comment by mk0x9** [comment]
@Pitometsu @lobachevzky @npostavs 

Is there any recipe for el-get for intero?

**Comment by Pitometsu** [comment]
```elisp
        (:name intero
               :type svn
               :url "https://github.com/commercialhaskell/intero/trunk/elisp"
               :description "Complete interactive development program for Haskell"
               :depends (flycheck company-mode))
```

**Comment by npostavs** [comment]
> ```emacs-lisp
>                :type svn
>                :url "https://github.com...
> ```

That can't be right, can it?

**Comment by Pitometsu** [comment]
Yes, it can :) That's my way to download only sub-directory of repository (because svn can, but git can not).
And one of nice features of github.

**Comment by npostavs** [comment]
Huh. TIL, as they say.

https://help.github.com/en/articles/support-for-subversion-clients
