### ISSUE TITLE
Symlinks to elpa package not created during `el-get-update`

### ISSUE THREAD

**Issue by maxchaos** [dimitri/el-get#2556]
Hi,

For some time now, I had noticed that executing `el-get-update-all` would fail while updating certain packages with an error complaining that no directory with the corresponding package's name could be found inside `el-get-dir`. I noticed that this error happened only during the update of packages fetched from elpa (as I had to manually fix the symlinks to their installation directories).

While having a quick look inside `methods/el-get-elpa.el`, I realized that the function `el-get-elpa-update` which is called to update such packages, after removing and re-installing the package (using `el-get-elpa-install-package` instead of `el-get-elpa-install`), never calls `el-get-elpa-symlink-package` on non-windows operating systems, and thus the symlink to the installation directory never gets created anew.

As a temporary fix, I tried placing `el-get-elpa-update`'s call to `el-get-elpa-symlink-package` outside the conditional statement and everything works fine now.

Being new to this and all, I don't really know what is the proper procedure for reporting/fixing this bug beyond this point.

**Comment by npostavs** [comment]
Hmm, I think you're right. Actually, I can't see why there is a conditional at all, we should update the symlinks regardless of platform.

> Being new to this and all, I don't really know what is the proper procedure for reporting/fixing this bug beyond this point.

Can you send a pull request?

**Comment by maxchaos** [comment]
Just did. Sorry for the delay.

Also, looking at the rest of the conditional, I also fail to understand it's purpose too (personally I am on a GNU/Linux machine and have no Windows installation available to test it out), because if I get right what `(delete-directory (el-get-elpa-package-directory package) t)` does is to delete the package's actual installation directory under `.emacs.d/elpa` (not the symlink under `el-get-dir`) right after it got re-installed by `el-get-elpa-install-package`.
