### ISSUE TITLE
el-get is causing problems in org-mode easy templates after update

### ISSUE THREAD

**Issue by renatocan** [dimitri/el-get#2577]
Since I've updated el-get last Friday, 11/10 org-mode easy templates stopped working.

Org-mode easy templates are keyboard shortcuts to insert empty pairs of some structural elements used in org-mode. One example is <s <TAB> which expands to the block #+BEGIN_SRC ... #+END_SRC. More information can be found in http://orgmode.org/manual/Easy-templates.html#Easy-templates

I'm running emacs with a minimum configuration in .emacs, just to enable el-get:

```
(add-to-list 'load-path "~/.emacs.d/el-get/el-get")

(unless (require 'el-get nil 'noerror)
  (require 'package)
  (add-to-list 'package-archives
               '("melpa" . "http://melpa.org/packages/"))
  (package-refresh-contents)
  (package-initialize)
  (package-install 'el-get)
  (require 'el-get))

(add-to-list 'el-get-recipe-path "~/.emacs.d/el-get-user/recipes")

(el-get 'sync)

```
I've noticed that when I comment the last line (el-get 'sync), org-mode easy templates back up and running.

Thanks!

[],

Renato.

**Comment by npostavs** [comment]
Do you have some version of org-mode in `~/.emacs.d/el-get/org-mode`?

**Comment by renatocan** [comment]
Yes, I do.

Actually, I've noticed some extra details.

Org-mode folder was installed previously, when I used my full configuration file. By cleaning .emacs.d, and using the config file I mentioned, the problem does not occur.

However, when I use the basic setup (not via MELPA) with the intallation of org-reveal, org-mode is downloaded (and ~/.emacs.d/el-get/org-mode is created) and the problem occurs. With a blank .emacs.d directory, it's possible to verify the problem with the following .emacs file

```
(add-to-list 'load-path "~/.emacs.d/el-get/el-get")

(unless (require 'el-get nil 'noerror)
  (with-current-buffer
      (url-retrieve-synchronously
       "https://raw.githubusercontent.com/dimitri/el-get/master/el-get-install.el")
    (goto-char (point-max))
    (eval-print-last-sexp)))

(add-to-list 'el-get-recipe-path "~/.emacs.d/el-get-user/recipes")

(el-get-bundle org-reveal)

(el-get 'sync)

```

If I use this same setup via MELPA, the problem does not occur but I have some problems with my full config (mainly related to Auctex - "File error: Cannot open load file, no such file or directory, tex-site"), so it would be nice to use basic setup via github.

Thanks,

[],

Renato.

**Comment by npostavs** [comment]
Does it work if you add `(setq org-reveal-note-key-char nil)`?
```elisp
(add-to-list 'load-path "~/.emacs.d/el-get/el-get")
[...]
(setq org-reveal-note-key-char nil)
(el-get-bundle org-reveal)

(el-get 'sync)
```

**Comment by renatocan** [comment]
No, it doesn't.

Thanks,
Renato.

**Comment by npostavs** [comment]
Seems to an org-mode bug, I updated to latest master, ran `make` and then `emacs -Q -L lisp/ -l lisp/org-loaddefs.el -f org-mode`. Entering `<s` `TAB` did not expand.

```
~/src/org-mode$ git log -1
commit 9cac9d7bc7e56c8cc3f67e29b791d4d2247f43b8
Merge: 4c703513a 3f8d67c49
Author: Nicolas Goaziou <mail@nicolasgoaziou.fr>
Date:   Sun Nov 12 23:29:38 2017 +0100

    Merge branch 'maint'
```

**Comment by renatocan** [comment]
Yes, It seems like an org-mode bug in the latest git commit. Using a previous version of org-mode avoids the problem. I installed org-mode with

```
(el-get-bundle! org-mode
  :checkout "release_9.1.2")
```
and could use the easy templates.

I've submitted a bug report to org-mode mailing list. I think we can close this issue.

Thanks,
[],

Renato.
