### ISSUE TITLE
Will using a git tag instead of a branch update when tag moves?

### ISSUE THREAD

**Issue by thoni56** [dimitri/el-get#2592]
I've started tagging the latest tested commit on my master with a "stable" tag that I move forward.

I was thinking this was a midway between locking to a particular version (and having to update el-get recipe for every version) and simply following the master branch.

Will this work? In the sense that when the tag moves el-get will update the installation in the same way as it does when a branch is used.

Should I use `:branch` or `:checkout` for this? The documentation seems to indicate that only `:checkout`can use tags, but it also indicates that that will lock the repo to that *revision*. So I'm wondering what happens when the tag moves.

**Comment by npostavs** [comment]
> So I'm wondering what happens when the tag moves.

Git tags aren't expected to move, so I suspect it would fail to update (possibly not, though; I haven't tried). 

Why not just make a "stable" branch instead of a tag? Git branches and tags are basically the same thing, apart from the git machinery which expects branches to be moveable.

**Comment by thoni56** [comment]
> Why not just make a "stable" branch instead of a tag?

Ok, I tried that and as I expected it was much harder for me to move a branch from the CI (Travis), possibly from my incomplete understanding of all intricacies of `git` (and possibly the Travis environment).

Of course this is not actually a topic for this repo, but what I tried was (when building on master)

    git branch -f stable master
    git checkout stable
    git push <URL>

and git insists that I have upstream changes that must be fetched first (as i understand it, on the stable branch), but a `git pull` before the push says "already up-to-date".

I'll take this question elsewhere.

**Comment by thoni56** [comment]
> Git tags aren't expected to move, so I suspect it would fail to update (possibly not, though; I haven't tried).

I'll take that as a "undefined behaviour" answer.

**Comment by npostavs** [comment]
Looking at what magit's `P e` (`magit-push-current`) does, I'm pretty you just need `git push <URL> master:refs/head/stable` or `git push -f <URL> master:refs/head/stable` if you want to ignore any extra commits.

**Comment by thoni56** [comment]
So you mean that `git push -f <URL> master:refs/head/stable` more or less is "ignore whatever stable was before, I really want it just to be pointing at whatever commit master is", in effect killing anything on the stable branch that might not have been on master and just setting it equal to master?

That would probably be exactly the semantics that I'm after, since any commit only on stable is in this scenario a mistake.

Thanks for the tip.

**Comment by npostavs** [comment]
> So you mean that git push -f <URL> master:refs/head/stable more or less is "ignore whatever stable was before, I really want it just to be pointing at whatever commit master is", in effect killing anything on the stable branch that might not have been on master and just setting it equal to master?

Basically, yes. Note that it sets the stable branch at `<URL>` based on what the local master branch is.

**Comment by thoni56** [comment]
NOTE to future readers: it should be `refs/heads/stable` (with an 's' in 'heads'). Without the `s` it creates a new branch ,-)

Maybe we should edit our comments.

**Comment by npostavs** [comment]
Argh, that's what I get for not copying directly from the `*magit-process` buffer. Fixed above.

**Comment by thoni56** [comment]
Yeah, the little things ...

Thanks for the help and the conversation!
