### ISSUE TITLE
Error installing zenburn with initialization code

### ISSUE THREAD

**Issue by mrDSide** [dimitri/el-get#2602]
When use this code on Windows 7 (32-bit):

`;; With initialization code`
`(el-get-bundle zenburn-theme`
`:url "https://raw.githubusercontent.com/bbatsov/zenburn-emacs/master/zenburn-theme.el"`
`(load-theme 'zenburn t))`

get error:

> Error (el-get): while initializing zenburn-theme: Unable to find theme file for ‘zenburn’

When copy file from directory "zenburn-theme" to "el-get" directory everything works fine.

> ~/.emacs.d/el-get/zenburn-theme/zenburn-theme.el
> ~/.emacs.d/el-get/zenburn-theme.el

**Comment by npostavs** [comment]
I think you need to add the package directory to `custom-theme-load-path`, something like this?
```
;; With initialization code
(el-get-bundle zenburn-theme
:url "https://raw.githubusercontent.com/bbatsov/zenburn-emacs/master/zenburn-theme.el"
(add-to-list 'custom-theme-load-path default-directory)
(load-theme 'zenburn t))
```
