### ISSUE TITLE
Install of auctex on termux fails

### ISSUE THREAD

**Issue by berenddeboer** [dimitri/el-get#2609]
Termux implements a very Linux like shell on Android. So I run emacs on it with el-get.

But auctex cannot be installed as it doesn't know its lisp path in this environment. The fix is easy, just like :build/darwin it just needs this parameter:

    "--with-lispdir=$(pwd)"

But I don't know what the build environment is for termux. If you can let me know I can fix this or we simply always set this parameter, it won't hurt I think.

**Comment by npostavs** [comment]
Looking at the `configure.ac` file, I don't see any `with-lispdir` option, so it's unclear to me how it could be doing anything.

**Comment by berenddeboer** [comment]
1. Look at auctex.rcp, this option is given to two other build targets.

2. It fixed the problem, and now installed.

**Comment by npostavs** [comment]
Oh, found it, it's hidden by some indirection. So probably all the variants should be passing `with-lispdir`, to keep things simpler.

`configure.ac`:
```
if test "X${packagedir}" = Xno
then
   EMACS_PATH_LISPDIR
```
`aclocal.m4`:
```
AC_DEFUN(EMACS_PATH_LISPDIR, [
  AC_MSG_CHECKING([where lisp files go])
  AC_ARG_WITH(lispdir,
    [  --with-lispdir=DIR      A place in load-path for Lisp files; most
                          files will be place in a subdirectory.],
    [[lispdir="${withval}"]])
  if test "X${lispdir}" = X; then
     if test "X${packagedir}" = Xno; then
       # Test paths relative to prefixes
       EMACS_EXAMINE_INSTALLATION_DIR(lispdir,
         [['${datadir}/'${EMACS_FLAVOR} '${libdir}/'${EMACS_FLAVOR} \
	   "${emacsprefix}/share/${EMACS_FLAVOR}" \
           '${datadir}' '${libdir}' "${emacsprefix}"]],
	 [[(list \"${EMACS_FLAVOR}/site-lisp\" \"${EMACS_FLAVOR}/site-packages\"
	         \"site-lisp\" \"site-packages\")]], load-path)
       if test "${lispdir}" = "NONE"; then
	 # No? notify user.
	 AC_MSG_ERROR([Cannot locate lisp directory,
use  --with-lispdir, --datadir, or possibly --prefix to rectify this])
       fi
     else
       # XEmacs
       lispdir="${packagedir}/lisp"
     fi
    fi
  AC_MSG_RESULT([[${lispdir}]])
  AC_SUBST(lispdir)
])
```

**Comment by npostavs** [comment]
I'm pretty sure the value passed to `--with-lispdir` doesn't matter though, since we don't do `make install`. So the only point of using the option is prevent `./configure` from failing.
