### ISSUE TITLE
Resource temporarily unavailable, try again

### ISSUE THREAD

**Issue by aurquiel** [dimitri/el-get#2617]
No matter how many i tried, it always showed unavailable

I run this in the buffer scratch

;; So the idea is that you copy/paste this code into your *scratch* buffer,
;; hit C-j, and you have a working el-get.
(url-retrieve
 "https://raw.githubusercontent.com/dimitri/el-get/master/el-get-install.el"
 (lambda (s)
   (goto-char (point-max))
   (eval-print-last-sexp)))

I wonder if the current url is ok

**Comment by npostavs** [comment]
Works for me. Do you have some firewalls blocking access maybe? Or it's a bug in url.el of the Emacs version you're using?

**Comment by aurquiel** [comment]
I have using linuxmint 18.3 i run

**sudo ufw disbale**

and i ouldn't neither fix the issue, my emacs --version is 

**GNU Emacs 24.5.1
Copyright (C) 2015 Free Software Foundation, Inc.
GNU Emacs comes with ABSOLUTELY NO WARRANTY.
You may redistribute copies of Emacs
under the terms of the GNU General Public License.
For more information about these matters, see the file named COPYING.**

how i could check if i have a bug with the url.el

**Comment by npostavs** [comment]
And no other messages? I think that means el-get is already installed.
