### ISSUE TITLE
emacs 26 on windows doesn't install elpa packages successfully

### ISSUE THREAD

**Issue by philipp** [dimitri/el-get#2633]
The call to "copy-directory" on line 143 of methods/el-get-elpa.el needs to have " nil t" added to the end of it so that the whole parent directory tree is created when copying it.
Otherwise, the install fails deep inside make-directory with a no such file or directory error.

Perhaps this changed because a (possibly long-standing) bug was fixed in emacs 26 where it was always creating the parent hierarchy if it didn't exist, even if the "parents" flag wasn't passed..

**Comment by philipp** [comment]
Maybe it's not really supposed to be doing the thing it's doing.
All elpa packages get dropped an additional subdirectory down.
Which, now that I look at it, causes problems after restarting emacs in any case.

Maybe the problem is that the additional level doesn't get stripped but previously it did?  Or perhaps I just never got elpa packages working at all before, and it's been a longer-standing issue?

With my fix, it puts things in places like:
* ~/.emacs.d/el-get/move-text/move-text-20170909.330/
* ~/.emacs.d/el-get/jq-mode/jq-mode-20180407.1048/

Which is why it has to be able to create the extra level.  So that's clearly the wrong place to fix it.  It just happens to work for the duration of the session when it was installed.

The error when I take the "nil t" out, looks like:
`make-directory: Creating directory: No such file or directory, d:/3p/.emacs.d/el-get/move-text/move-text-20170909.330`

Okay, further playing around indicates that it will do what I believe to be the Right Thing by adding `nil nil t` to the end of the `copy-directory` call.
That will tell it not to copy the directory itself, but the *contents* of the directory.
That way I end up with files in just the top level package name folder, rather than that versioned/timestamped sub one.

Hope that helps out a little.

**Comment by NingyuShi** [comment]
I agree with @philipp . After adding `nil nil t` to `copy-directory` call, it works for me on windows.

**Comment by npostavs** [comment]
> Okay, further playing around indicates that it will do what I believe to be the Right Thing by adding `nil nil t` to the end of the `copy-directory` call.
> That will tell it not to copy the directory itself, but the _contents_ of the directory.

Hmm, the docstring of `copy-directory` says:
```
If NEWNAME names an existing directory, copy DIRECTORY as a
subdirectory there.  However, if called from Lisp with a non-nil
optional argument COPY-CONTENTS, copy the contents of DIRECTORY
directly into NEWNAME instead.
```
So I think it normally works because `NEWNAME` doesn't exist (e.g., `el-get-elpa-update` calls `el-get-elpa-remove` before `el-get-elpa-symlink-package`). I agree that it makes sense to pass this argument so we get the right behaviour all the time, but I'm a bit curious how you managed to get into the situation where you call `el-get-elpa-symlink-package` and the directory already exists.

**Comment by NingyuShi** [comment]
@npostavs In my case, my git call fails for me because of wrong exe it found. Some previous operation failed, and it caused the dir to be there.

**Comment by philipp** [comment]
> > Okay, further playing around indicates that it will do what I believe to be the Right Thing by adding `nil nil t` to the end of the `copy-directory` call.
> > That will tell it not to copy the directory itself, but the _contents_ of the directory.
> 
> Hmm, the docstring of `copy-directory` says:
> 
> ```
> If NEWNAME names an existing directory, copy DIRECTORY as a
> subdirectory there.  However, if called from Lisp with a non-nil
> optional argument COPY-CONTENTS, copy the contents of DIRECTORY
> directly into NEWNAME instead.
> ```
> So I think it normally works because `NEWNAME` doesn't exist (e.g., `el-get-elpa-update` calls `el-get-elpa-remove` before `el-get-elpa-symlink-package`). I agree that it makes sense to pass this argument so we get the right behaviour all the time, but I'm a bit curious how you managed to get into the situation where you call `el-get-elpa-symlink-package` and the directory already exists.

Aha!
And perhaps the answer is in the docstring you quoted.
My docstring in Emacs 26 (difference bolded) reads like this:

```
**If NEWNAME is a directory name**, copy DIRECTORY as a subdirectory
there.  However, if called from Lisp with a non-nil optional
argument COPY-CONTENTS, copy the contents of DIRECTORY directly
into NEWNAME instead.
```

And I see starting on [line 1131 in the Emacs 26 NEWS file](https://github.com/emacs-mirror/emacs/blob/7f3877e83405a089b580fe9d0342dc0b6c08cbfc/etc/NEWS.26#L1311) that there are some changes that cleaned up inconsistencies and undocumented behavior in functions (including `copy-directory`) that deal with directory names as arguments.

So that may be the real reason for the difference in behavior.
I don't know whether the directory is there yet at the time copy-directory is called.  But I'm guessing it doesn't.
Most likely, [this](https://github.com/emacs-mirror/emacs/commit/e22794867d878d53675fcc91d2ef1ad2494a2ff2) is the commit that changed things, though there were a few others around the same time that might subtly affect the behavior.

Also, in case this is helpful, I did dump out all the parameters that go into it when it runs for me:

```
package is ‘move-text’
expand-file-name is ‘d:/3p/.emacs.d/el-get/move-text’
as directory is ‘d:/3p/.emacs.d/el-get/move-text/’
elpa-dir is ‘d:/3p/.emacs.d/elpa/move-text-20170909.330’
```

**Comment by npostavs** [comment]
> And I see starting on [line 1131 in the Emacs 26 NEWS file](https://github.com/emacs-mirror/emacs/blob/7f3877e83405a089b580fe9d0342dc0b6c08cbfc/etc/NEWS.26#L1311) that there are some changes that cleaned up inconsistencies and undocumented behavior in functions (including `copy-directory`) that deal with directory names as arguments.
> 
> So that may be the real reason for the difference in behavior.

Oh, right, that explains it, thanks. I haven't fully migrated my Windows box to Emacs 26 yet, so I didn't see the problem. Trying it now on v26 I see it immediately.
