### ISSUE TITLE
Magit installation is missing dependencies: graphql and treepy

### ISSUE THREAD

**Issue by vmiheer** [dimitri/el-get#2646]
On executing `magit-status`, it says no such file `graphql` and shows incomplete status.
On installation of `graphql` and `treepy` using `package-install` it shows whole status.

**Comment by sakh1979** [comment]
If someone can point me in right direction, I can work on the fix. I need `magit` working as well.

**Comment by sakh1979** [comment]
I am confused on how to add `graphql` and 'treepy` as dependencies to magit's recipe. If I create the two new recipes will it solve the issue?

Additionally, is there any documentation on how to locally add, and test new recipes?

**Comment by npostavs** [comment]
> If I create the two new recipes will it solve the issue?

You have to reference them in magit.rcp's `:depends` entry too.

> Additionally, is there any documentation on how to locally add, and test new recipes?

See the "Authoring Recipes" node in the manual.

**Comment by sakh1979** [comment]
@npostavs did you get a chance to look at the pull request?
