### ISSUE TITLE
request: sound-wav.el

### ISSUE THREAD

**Issue by vmiheer** [dimitri/el-get#2657]
https://github.com/syohex/emacs-sound-wav/blob/master/sound-wav.el
This is available as `package-install`.

**Comment by AndersonTorres** [comment]
Now you can close it :)

**Comment by vmiheer** [comment]
I was wondering if el-get has capability to specify target specific dependencies?
e.g. in the same file:
```elisp
(when (memq system-type '(windows-nt ms-dos))
 (require 'powershell nil t))
```

**Comment by npostavs** [comment]
> I was wondering if el-get has capability to specify target specific dependencies?

No, it doesn't.

**Comment by vmiheer** [comment]
Thank you.
