### ISSUE TITLE
el-get forgets to add loadpaths

### ISSUE THREAD

**Issue by zilti** [dimitri/el-get#2681]
Since a few weeks, I have the problem that `cider` has stopped working as a package - it works when it initially gets installed, but on each subsequent Emacs launch, I'm greeted with `Cannot open load file: file or directory not found, cider`. I temporarily fixed this by adding `~/.emacs.d/el-get/cider` to the `load-path` variable manually. But I don't understand why it stopped working so suddenly.

What's more, as soon as I added this line and restarted Emacs, I got instead a "Cannot open load file" for the package "spinner". So it seems to not be just a cider recipe problem.

**Comment by npostavs** [comment]
el-get hasn't changed recently, so it must be a change in your config. I don't think you've posted enough info for anyone else to figure it out though.
