### ISSUE TITLE
el-get sync trying to load mac-classic-theme

### ISSUE THREAD

**Issue by rhoit** [dimitri/el-get#2695]
I update the el-get (a0fe1f7c375b17e9) today, but met with disappointment. when el-get sync it trying to load  `mac-classic-theme` which I don't even use.  I had to manually clone [mac-classic-theme](https://github.com/ahobson/mac-classic-theme) `load-path'  just to get thing working.

![image](https://user-images.githubusercontent.com/1684754/55290349-e2df0080-53f1-11e9-92aa-b2675da5c8e0.png)

Is there any way out for this, not really sure why `(el-get 'sync)` is trying to get theme.

**Comment by npostavs** [comment]
It looks like one of the packages you installed tries to modify the theme in an `;;;###autoload` cookie. Can you find the `(custom-theme-set-faces 'mac-classic ...)` call in your `~/.emacs.d/el-get/.loaddefs.el` file? There should be a `;;; Generated autoloads from foo/bar.el` line above it which says which package it came from.

**Comment by rhoit** [comment]
I just deleted the following line `el-get-update-all` every thing is ok now, not even sure how it happened.


    ;;;***
    
    ;;;### (autoloads nil "mac-classic-theme/mac-classic-theme" "mac-classic-theme/mac-classic-theme.el"
    ;;;;;;  (0 0 0 0))
    ;;; Generated autoloads from mac-classic-theme/mac-classic-theme.el
     
    (custom-theme-set-faces 'mac-classic '(default ((t (:background "white" :foreground "black")))) '(font-lock-builtin-face ((t (:foreground "#0000CD" :bold t)))) '(font-lock-constant-face ((t (:foreground "#C5060B" :bold t)))) '(font-lock-preprocessor-face ((t (:foreground "#3596A4")))) '(font-lock-keyword-face ((t (:foreground "#0000FF" :bold t)))) '(font-lock-type-face ((t (:foreground "#585CF6" :bold t)))) '(font-lock-variable-name-face ((t (:foreground "#318495")))) '(font-lock-function-name-face ((t (:foreground "#0000A2" :bold t)))) '(font-lock-string-face ((t (:foreground "#036A07")))) '(ruby-string-variable-face ((t (:foreground "#26B31A")))) '(font-lock-comment-face ((t (:foreground "#0066FF" :italic t)))) '(font-lock-comment-delimiter-face ((t (:foreground "#0066FF")))) '(whitespace-trailing ((t (:background "#FFD0D0")))) '(font-lock-doc-face ((t (:italic t :slant oblique :foreground "#B90690")))) '(font-lock-doc-string-face ((t (:foreground "#B90690")))))
     
    (if (fboundp 'register-definition-prefixes) (register-definition-prefixes "mac-classic-theme/mac-classic-theme" '("mac-classic")))
