### ISSUE TITLE
Cannot load "s" after installing groovy-emacs-mode

### ISSUE THREAD

**Issue by pedz** [dimitri/el-get#2709]
I updated to the latest el-get.  I go into el-get-list-packages and mark groovy-emacs-mode to be installed.  I can also mark "s" to be installed or not but it doesn't make any difference.

When I am finished, groovy-emacs-mode works fine.  But if I quit emacs and start it back up, when I open a file that tries to use groovy-emacs-mode, I get this error:

    File mode specification error: (file-missing Cannot open load file No such file or directory s)

The work around I do is to add the el-get/s directory into my load-path which gets me working for now but I thought you guys might like to know.

**Comment by npostavs** [comment]
You need to put `(el-get 'sync)` in your init file, as explained in https://github.com/dimitri/el-get#setup.

**Comment by pedz** [comment]
Thank you.  I was attempting to do the [Advanced Usage with Local Recipes](https://github.com/dimitri/el-get#advanced-usage-with-local-recipes) but didn't 100% understand it (or remember that I was doing it).  I see now that I can sorta have my cake and eat it too by putting `(el-get 'sync)` after the `el-get-bundle` calls.

Thank you again.  Its super nice to be able to add things like Groovy syntax highlighting by just picking a package.  Much better than the old days before emacs packages.

**Comment by npostavs** [comment]
Oh, I see.  I've updated that section of the README to clarify that
`(el-get 'sync)` is required unless you keep track of dependencies
yourself.

**Comment by pedz** [comment]
Slight change of topic.  Another symptom I saw before was el-get was not in my Info list.  Now it is.  I was going to read up on recipes to see if the 's' recipe needed to be modified is how I noticed.

Is that something else that `(el-get `sync)` does?

Hope this helps

**Comment by npostavs** [comment]
> Is that something else that `(el-get 'sync)` does?

Yes, it will setup any el-get package that you have installed, which includes itself.
