### ISSUE TITLE
Installing El-Get on Windows

### ISSUE THREAD

**Issue by tajmone** [dimitri/el-get#2713]
The Wiki page [Installation on Windows] should be updated.

I've just installed successfully el-get using an out-of-the-box Emacs for Windows (v26.2, with all deps) on Win 10 x64, without following the instructions of the Wiki page.

I've just pasted the "Lazy installer" snippet into the  `*scratch*` buffer, evaluated it and that was that — happily got the message:

> Congrats, el-get is installed and ready to serve!nil

I didn't want to edit the Wiki page myself for two reasons:

1. This is my first brush with both Emacs and el-get (so chances are that beside the happy-end message above, things might not be working 100%).
2. Editing the page would basically mean taking it over — and possibly what's said there might still hold true for older Windows versions (I just don't know).

But I though it was worth sharing this with you.

[Installation on Windows]: https://github.com/dimitri/el-get/wiki/Installation-on-Windows

**Comment by npostavs** [comment]
> (v26.2, with all deps)

Ah right, previous Emacs releases didn't come with the deps. I've updated the wiki page to mention that.
