### ISSUE TITLE
Certain packages installed but not usable

### ISSUE THREAD

**Issue by minikN** [dimitri/el-get#2747]
Hello, after starting to migrate my config to `el-get` I noticed that some packages seem to get installed correctly, but are, for some reason not usable.

The packages I've encountered so far are: `popup-kill-ring` and `org-pdfview`.
They (I guess) get installed correctly. A `el-get-describe popup-kill-ring` tells me the package is installed. I can also see it inside `~/.emacs.d/el-get` alongside it's dependencies.

However, with `popup-kill-ring` I should have access to a function `popup-kill-ring` to invoke it. I don't: `popup-kill-ring is not a valid command name`.

The same happens with `org-pdfview`: It seems to be installed correctly, but I should be able to open a pdf file with `org-pdfview-open <file>`. Again not a valid command name.

Maybe I'm misunderstanding something here. 

Snippets used for `popup-kill-ring`:
```
(el-get-bundle popup-kill-ring
  (global-set-key (kbd "M-y") #'popup-kill-ring))
```
Additional info: `(featurep 'popup-kill-ring)` evaluates to `nil`. Why?

`emacs --version`: `26.3`
`el-get-version`: `5.1.f6408024`

When I search for `popup` in `.loaddefs.el`, the following are all occurences:
```
;;;### (autoloads nil "popup-kill-ring/popup-kill-ring" "popup-kill-ring/popup-kill-ring.el"
;;;;;;  (0 0 0 0))
;;; Generated autoloads from popup-kill-ring/popup-kill-ring.el

(if (fboundp 'register-definition-prefixes) (register-definition-prefixes "popup-kill-ring/popup-kill-ring" '("popup-kill-ring")))

;;;***

;;;### (autoloads nil "popup/popup" "popup/popup.el" (0 0 0 0))
;;; Generated autoloads from popup/popup.el

(if (fboundp 'register-definition-prefixes) (register-definition-prefixes "popup/popup" '("popup-")))
```
Also, `M-:` `(el-get-invalidate-autoloads)` doesn't help.

**Comment by stephan-cr** [comment]
The recipe for popup-kill-ring points to [Emacs Wiki](https://www.emacswiki.org/emacs/popup-kill-ring.el). This version lacks any autoload. There's another one on [Github](https://github.com/waymondo/popup-kill-ring), which has a autoload, but is not in sync with the Emacs Wiki version. The Wiki has more recent changes.

May

**Comment by stephan-cr** [comment]
Not sure where you found the recipe for org-pdfview.
