### ISSUE TITLE
Add "when" to "define-obsolete-function-alias" in el-get-status.el

### ISSUE THREAD

**Issue by jeffkowalski** [dimitri/el-get#2795]
A recent change in Emacs 28 has made the third argument (WHEN) of define-obsolete-function-alias mandatory. Code that depends on list-utils.el gets repeated error messages because of two uses of that function with only the old-name and new-name signature. The problem is easy to fix: add a date to the definition.

See https://github.com/dimitri/el-get/blob/6138ce5b0a9df779e33ef42eadc4c15a5cf65f39/el-get-status.el#L176

**Comment by stephan-cr** [comment]
This issue is fixed in #2801.
