### ISSUE TITLE
Compilation fix for Emacs 28 native-comp branch breaks build for all the other Emacs versions

### ISSUE THREAD

**Issue by stephan-cr** [dimitri/el-get#2833]
@tarao @vedang PR #2801 might fix compilation for Emacs 28 native-comp branch, but breaks the build for all the other Emacs versions.

**Comment by abdrus** [comment]
Confirmed on my doom emacs v26.3.

Launching `emacs --debug-init` shows

> Debugger entered--Lisp error: (file-missing "Cannot open load file" "No such file or directory" "/home/abdrus/.emacs.d/.local/autoloads.26.3")

Running `doom doctor` shows
`
x There was an unexpected error
  Message: error
  Data: (error . "Invalid value (1 single-branch) of depth for https://github.com/dimitri/el-get.git")
  Backtrace:
    (signal error ("Invalid value (1 single-branch) of depth for https://githu
    (error "Invalid value %S of depth for %s" (1 single-branch) "https://githu
    (cond ((eq depth (quote full)) (straight--get-call "git" "clone" "--origin
    (progn (let ((--cl-keys-- --cl-rest--)) (while --cl-keys-- (cond ((memq (c
    (let* ((depth (car (cdr (plist-member --cl-rest-- (quote :depth))))) (remo
    (straight-vc-git--clone-internal :depth (1 single-branch) :remote "origin"
    (progn (straight-vc-git--clone-internal :depth depth :remote remote :url u
    (unwind-protect (progn (straight-vc-git--clone-internal :depth depth :remo
    (let ((success nil) (repo-dir (straight--repos-dir local-repo)) (url (stra
    (let ((package (plist-get --recipe-- (quote :package))) (local-repo (plist
`
