### ISSUE TITLE
Incorrect recipe for git-timemachine

### ISSUE THREAD

**Issue by polaris64** [dimitri/el-get#2879]
https://github.com/dimitri/el-get/blob/master/recipes/git-timemachine.rcp currently points to https://gitlab.com/pidu/git-timemachine, however this now contains only a single file ([README.md](https://gitlab.com/pidu/git-timemachine/-/blob/master/README.md)) which states that the project has been moved to https://codeberg.org/pidu/git-timemachine

**Comment by alexott** [comment]
already fixed
